/**
 * LogisticsService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RailWaybillDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



RailWaybillDto::RailWaybillDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_DocumentNumber = utility::conversions::to_string_t("");
    m_DocumentNumberIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_ShipperContactId = utility::conversions::to_string_t("");
    m_ShipperContactIdIsSet = false;
    m_ConsigneeContactId = utility::conversions::to_string_t("");
    m_ConsigneeContactIdIsSet = false;
    m_CarrierId = utility::conversions::to_string_t("");
    m_CarrierIdIsSet = false;
    m_RailOperatorName = utility::conversions::to_string_t("");
    m_RailOperatorNameIsSet = false;
    m_StationOfDeparture = utility::conversions::to_string_t("");
    m_StationOfDepartureIsSet = false;
    m_StationOfDepartureCode = utility::conversions::to_string_t("");
    m_StationOfDepartureCodeIsSet = false;
    m_StationOfDestination = utility::conversions::to_string_t("");
    m_StationOfDestinationIsSet = false;
    m_StationOfDestinationCode = utility::conversions::to_string_t("");
    m_StationOfDestinationCodeIsSet = false;
    m_PrescribedRoute = utility::conversions::to_string_t("");
    m_PrescribedRouteIsSet = false;
    m_WagonNumbers = utility::conversions::to_string_t("");
    m_WagonNumbersIsSet = false;
    m_DateOfAcceptance = utility::datetime();
    m_DateOfAcceptanceIsSet = false;
    m_DateOfDelivery = utility::datetime();
    m_DateOfDeliveryIsSet = false;
    m_FreightTerms = utility::conversions::to_string_t("");
    m_FreightTermsIsSet = false;
    m_FreightAmount = 0.0;
    m_FreightAmountIsSet = false;
    m_FreightCurrencyId = utility::conversions::to_string_t("");
    m_FreightCurrencyIdIsSet = false;
    m_TotalGrossWeightKg = 0.0;
    m_TotalGrossWeightKgIsSet = false;
    m_TotalPackages = 0;
    m_TotalPackagesIsSet = false;
    m_TotalVolumeM3 = 0.0;
    m_TotalVolumeM3IsSet = false;
    m_CustomsFormalities = utility::conversions::to_string_t("");
    m_CustomsFormalitiesIsSet = false;
    m_SpecialInstructions = utility::conversions::to_string_t("");
    m_SpecialInstructionsIsSet = false;
    m_Remarks = utility::conversions::to_string_t("");
    m_RemarksIsSet = false;
    m_SenderSignedDate = utility::datetime();
    m_SenderSignedDateIsSet = false;
    m_CarrierSignedDate = utility::datetime();
    m_CarrierSignedDateIsSet = false;
    m_ShipmentId = utility::conversions::to_string_t("");
    m_ShipmentIdIsSet = false;
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
    m_EnrollmentId = utility::conversions::to_string_t("");
    m_EnrollmentIdIsSet = false;
    m_LinesIsSet = false;
}

RailWaybillDto::~RailWaybillDto()
{
}

void RailWaybillDto::validate()
{
    // TODO: implement validation
}

web::json::value RailWaybillDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_DocumentNumberIsSet)
    {
        val[utility::conversions::to_string_t(U("documentNumber"))] = ModelBase::toJson(m_DocumentNumber);
    }
    if(m_StatusIsSet)
    {
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_ShipperContactIdIsSet)
    {
        val[utility::conversions::to_string_t(U("shipperContactId"))] = ModelBase::toJson(m_ShipperContactId);
    }
    if(m_ConsigneeContactIdIsSet)
    {
        val[utility::conversions::to_string_t(U("consigneeContactId"))] = ModelBase::toJson(m_ConsigneeContactId);
    }
    if(m_CarrierIdIsSet)
    {
        val[utility::conversions::to_string_t(U("carrierId"))] = ModelBase::toJson(m_CarrierId);
    }
    if(m_RailOperatorNameIsSet)
    {
        val[utility::conversions::to_string_t(U("railOperatorName"))] = ModelBase::toJson(m_RailOperatorName);
    }
    if(m_StationOfDepartureIsSet)
    {
        val[utility::conversions::to_string_t(U("stationOfDeparture"))] = ModelBase::toJson(m_StationOfDeparture);
    }
    if(m_StationOfDepartureCodeIsSet)
    {
        val[utility::conversions::to_string_t(U("stationOfDepartureCode"))] = ModelBase::toJson(m_StationOfDepartureCode);
    }
    if(m_StationOfDestinationIsSet)
    {
        val[utility::conversions::to_string_t(U("stationOfDestination"))] = ModelBase::toJson(m_StationOfDestination);
    }
    if(m_StationOfDestinationCodeIsSet)
    {
        val[utility::conversions::to_string_t(U("stationOfDestinationCode"))] = ModelBase::toJson(m_StationOfDestinationCode);
    }
    if(m_PrescribedRouteIsSet)
    {
        val[utility::conversions::to_string_t(U("prescribedRoute"))] = ModelBase::toJson(m_PrescribedRoute);
    }
    if(m_WagonNumbersIsSet)
    {
        val[utility::conversions::to_string_t(U("wagonNumbers"))] = ModelBase::toJson(m_WagonNumbers);
    }
    if(m_DateOfAcceptanceIsSet)
    {
        val[utility::conversions::to_string_t(U("dateOfAcceptance"))] = ModelBase::toJson(m_DateOfAcceptance);
    }
    if(m_DateOfDeliveryIsSet)
    {
        val[utility::conversions::to_string_t(U("dateOfDelivery"))] = ModelBase::toJson(m_DateOfDelivery);
    }
    if(m_FreightTermsIsSet)
    {
        val[utility::conversions::to_string_t(U("freightTerms"))] = ModelBase::toJson(m_FreightTerms);
    }
    if(m_FreightAmountIsSet)
    {
        val[utility::conversions::to_string_t(U("freightAmount"))] = ModelBase::toJson(m_FreightAmount);
    }
    if(m_FreightCurrencyIdIsSet)
    {
        val[utility::conversions::to_string_t(U("freightCurrencyId"))] = ModelBase::toJson(m_FreightCurrencyId);
    }
    if(m_TotalGrossWeightKgIsSet)
    {
        val[utility::conversions::to_string_t(U("totalGrossWeightKg"))] = ModelBase::toJson(m_TotalGrossWeightKg);
    }
    if(m_TotalPackagesIsSet)
    {
        val[utility::conversions::to_string_t(U("totalPackages"))] = ModelBase::toJson(m_TotalPackages);
    }
    if(m_TotalVolumeM3IsSet)
    {
        val[utility::conversions::to_string_t(U("totalVolumeM3"))] = ModelBase::toJson(m_TotalVolumeM3);
    }
    if(m_CustomsFormalitiesIsSet)
    {
        val[utility::conversions::to_string_t(U("customsFormalities"))] = ModelBase::toJson(m_CustomsFormalities);
    }
    if(m_SpecialInstructionsIsSet)
    {
        val[utility::conversions::to_string_t(U("specialInstructions"))] = ModelBase::toJson(m_SpecialInstructions);
    }
    if(m_RemarksIsSet)
    {
        val[utility::conversions::to_string_t(U("remarks"))] = ModelBase::toJson(m_Remarks);
    }
    if(m_SenderSignedDateIsSet)
    {
        val[utility::conversions::to_string_t(U("senderSignedDate"))] = ModelBase::toJson(m_SenderSignedDate);
    }
    if(m_CarrierSignedDateIsSet)
    {
        val[utility::conversions::to_string_t(U("carrierSignedDate"))] = ModelBase::toJson(m_CarrierSignedDate);
    }
    if(m_ShipmentIdIsSet)
    {
        val[utility::conversions::to_string_t(U("shipmentId"))] = ModelBase::toJson(m_ShipmentId);
    }
    if(m_TenantIdIsSet)
    {
        val[utility::conversions::to_string_t(U("tenantId"))] = ModelBase::toJson(m_TenantId);
    }
    if(m_EnrollmentIdIsSet)
    {
        val[utility::conversions::to_string_t(U("enrollmentId"))] = ModelBase::toJson(m_EnrollmentId);
    }
    if(m_LinesIsSet)
    {
        val[utility::conversions::to_string_t(U("lines"))] = ModelBase::toJson(m_Lines);
    }

    return val;
}

bool RailWaybillDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("documentNumber"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("documentNumber")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDocumentNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDocumentNumber);
            setDocumentNumber(refVal_setDocumentNumber);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("shipperContactId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("shipperContactId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setShipperContactId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipperContactId);
            setShipperContactId(refVal_setShipperContactId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("consigneeContactId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("consigneeContactId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setConsigneeContactId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConsigneeContactId);
            setConsigneeContactId(refVal_setConsigneeContactId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("carrierId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("carrierId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCarrierId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCarrierId);
            setCarrierId(refVal_setCarrierId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("railOperatorName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("railOperatorName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRailOperatorName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRailOperatorName);
            setRailOperatorName(refVal_setRailOperatorName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("stationOfDeparture"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("stationOfDeparture")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationOfDeparture;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationOfDeparture);
            setStationOfDeparture(refVal_setStationOfDeparture);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("stationOfDepartureCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("stationOfDepartureCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationOfDepartureCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationOfDepartureCode);
            setStationOfDepartureCode(refVal_setStationOfDepartureCode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("stationOfDestination"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("stationOfDestination")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationOfDestination;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationOfDestination);
            setStationOfDestination(refVal_setStationOfDestination);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("stationOfDestinationCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("stationOfDestinationCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationOfDestinationCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationOfDestinationCode);
            setStationOfDestinationCode(refVal_setStationOfDestinationCode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("prescribedRoute"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("prescribedRoute")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPrescribedRoute;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrescribedRoute);
            setPrescribedRoute(refVal_setPrescribedRoute);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("wagonNumbers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("wagonNumbers")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWagonNumbers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWagonNumbers);
            setWagonNumbers(refVal_setWagonNumbers);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("dateOfAcceptance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("dateOfAcceptance")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDateOfAcceptance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDateOfAcceptance);
            setDateOfAcceptance(refVal_setDateOfAcceptance);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("dateOfDelivery"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("dateOfDelivery")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDateOfDelivery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDateOfDelivery);
            setDateOfDelivery(refVal_setDateOfDelivery);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("freightTerms"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("freightTerms")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFreightTerms;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFreightTerms);
            setFreightTerms(refVal_setFreightTerms);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("freightAmount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("freightAmount")));
        if(!fieldValue.is_null())
        {
            double refVal_setFreightAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFreightAmount);
            setFreightAmount(refVal_setFreightAmount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("freightCurrencyId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("freightCurrencyId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFreightCurrencyId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFreightCurrencyId);
            setFreightCurrencyId(refVal_setFreightCurrencyId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("totalGrossWeightKg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("totalGrossWeightKg")));
        if(!fieldValue.is_null())
        {
            double refVal_setTotalGrossWeightKg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalGrossWeightKg);
            setTotalGrossWeightKg(refVal_setTotalGrossWeightKg);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("totalPackages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("totalPackages")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalPackages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalPackages);
            setTotalPackages(refVal_setTotalPackages);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("totalVolumeM3"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("totalVolumeM3")));
        if(!fieldValue.is_null())
        {
            double refVal_setTotalVolumeM3;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalVolumeM3);
            setTotalVolumeM3(refVal_setTotalVolumeM3);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("customsFormalities"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("customsFormalities")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomsFormalities;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomsFormalities);
            setCustomsFormalities(refVal_setCustomsFormalities);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("specialInstructions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("specialInstructions")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSpecialInstructions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSpecialInstructions);
            setSpecialInstructions(refVal_setSpecialInstructions);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("remarks"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("remarks")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRemarks;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRemarks);
            setRemarks(refVal_setRemarks);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("senderSignedDate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("senderSignedDate")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setSenderSignedDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSenderSignedDate);
            setSenderSignedDate(refVal_setSenderSignedDate);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("carrierSignedDate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("carrierSignedDate")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCarrierSignedDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCarrierSignedDate);
            setCarrierSignedDate(refVal_setCarrierSignedDate);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("shipmentId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("shipmentId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setShipmentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipmentId);
            setShipmentId(refVal_setShipmentId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("enrollmentId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("enrollmentId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnrollmentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnrollmentId);
            setEnrollmentId(refVal_setEnrollmentId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("lines"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("lines")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<WaybillLineDto>> refVal_setLines;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLines);
            setLines(refVal_setLines);
        }
    }
    return ok;
}

void RailWaybillDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_DocumentNumberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("documentNumber")), m_DocumentNumber));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
    if(m_ShipperContactIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("shipperContactId")), m_ShipperContactId));
    }
    if(m_ConsigneeContactIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("consigneeContactId")), m_ConsigneeContactId));
    }
    if(m_CarrierIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("carrierId")), m_CarrierId));
    }
    if(m_RailOperatorNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("railOperatorName")), m_RailOperatorName));
    }
    if(m_StationOfDepartureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("stationOfDeparture")), m_StationOfDeparture));
    }
    if(m_StationOfDepartureCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("stationOfDepartureCode")), m_StationOfDepartureCode));
    }
    if(m_StationOfDestinationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("stationOfDestination")), m_StationOfDestination));
    }
    if(m_StationOfDestinationCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("stationOfDestinationCode")), m_StationOfDestinationCode));
    }
    if(m_PrescribedRouteIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("prescribedRoute")), m_PrescribedRoute));
    }
    if(m_WagonNumbersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("wagonNumbers")), m_WagonNumbers));
    }
    if(m_DateOfAcceptanceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("dateOfAcceptance")), m_DateOfAcceptance));
    }
    if(m_DateOfDeliveryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("dateOfDelivery")), m_DateOfDelivery));
    }
    if(m_FreightTermsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("freightTerms")), m_FreightTerms));
    }
    if(m_FreightAmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("freightAmount")), m_FreightAmount));
    }
    if(m_FreightCurrencyIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("freightCurrencyId")), m_FreightCurrencyId));
    }
    if(m_TotalGrossWeightKgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("totalGrossWeightKg")), m_TotalGrossWeightKg));
    }
    if(m_TotalPackagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("totalPackages")), m_TotalPackages));
    }
    if(m_TotalVolumeM3IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("totalVolumeM3")), m_TotalVolumeM3));
    }
    if(m_CustomsFormalitiesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("customsFormalities")), m_CustomsFormalities));
    }
    if(m_SpecialInstructionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("specialInstructions")), m_SpecialInstructions));
    }
    if(m_RemarksIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("remarks")), m_Remarks));
    }
    if(m_SenderSignedDateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("senderSignedDate")), m_SenderSignedDate));
    }
    if(m_CarrierSignedDateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("carrierSignedDate")), m_CarrierSignedDate));
    }
    if(m_ShipmentIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("shipmentId")), m_ShipmentId));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tenantId")), m_TenantId));
    }
    if(m_EnrollmentIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("enrollmentId")), m_EnrollmentId));
    }
    if(m_LinesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("lines")), m_Lines));
    }
}

bool RailWaybillDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("documentNumber"))))
    {
        utility::string_t refVal_setDocumentNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("documentNumber"))), refVal_setDocumentNumber );
        setDocumentNumber(refVal_setDocumentNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("shipperContactId"))))
    {
        utility::string_t refVal_setShipperContactId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("shipperContactId"))), refVal_setShipperContactId );
        setShipperContactId(refVal_setShipperContactId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("consigneeContactId"))))
    {
        utility::string_t refVal_setConsigneeContactId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("consigneeContactId"))), refVal_setConsigneeContactId );
        setConsigneeContactId(refVal_setConsigneeContactId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("carrierId"))))
    {
        utility::string_t refVal_setCarrierId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("carrierId"))), refVal_setCarrierId );
        setCarrierId(refVal_setCarrierId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("railOperatorName"))))
    {
        utility::string_t refVal_setRailOperatorName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("railOperatorName"))), refVal_setRailOperatorName );
        setRailOperatorName(refVal_setRailOperatorName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("stationOfDeparture"))))
    {
        utility::string_t refVal_setStationOfDeparture;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("stationOfDeparture"))), refVal_setStationOfDeparture );
        setStationOfDeparture(refVal_setStationOfDeparture);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("stationOfDepartureCode"))))
    {
        utility::string_t refVal_setStationOfDepartureCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("stationOfDepartureCode"))), refVal_setStationOfDepartureCode );
        setStationOfDepartureCode(refVal_setStationOfDepartureCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("stationOfDestination"))))
    {
        utility::string_t refVal_setStationOfDestination;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("stationOfDestination"))), refVal_setStationOfDestination );
        setStationOfDestination(refVal_setStationOfDestination);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("stationOfDestinationCode"))))
    {
        utility::string_t refVal_setStationOfDestinationCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("stationOfDestinationCode"))), refVal_setStationOfDestinationCode );
        setStationOfDestinationCode(refVal_setStationOfDestinationCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("prescribedRoute"))))
    {
        utility::string_t refVal_setPrescribedRoute;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("prescribedRoute"))), refVal_setPrescribedRoute );
        setPrescribedRoute(refVal_setPrescribedRoute);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("wagonNumbers"))))
    {
        utility::string_t refVal_setWagonNumbers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("wagonNumbers"))), refVal_setWagonNumbers );
        setWagonNumbers(refVal_setWagonNumbers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("dateOfAcceptance"))))
    {
        utility::datetime refVal_setDateOfAcceptance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("dateOfAcceptance"))), refVal_setDateOfAcceptance );
        setDateOfAcceptance(refVal_setDateOfAcceptance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("dateOfDelivery"))))
    {
        utility::datetime refVal_setDateOfDelivery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("dateOfDelivery"))), refVal_setDateOfDelivery );
        setDateOfDelivery(refVal_setDateOfDelivery);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("freightTerms"))))
    {
        utility::string_t refVal_setFreightTerms;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("freightTerms"))), refVal_setFreightTerms );
        setFreightTerms(refVal_setFreightTerms);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("freightAmount"))))
    {
        double refVal_setFreightAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("freightAmount"))), refVal_setFreightAmount );
        setFreightAmount(refVal_setFreightAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("freightCurrencyId"))))
    {
        utility::string_t refVal_setFreightCurrencyId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("freightCurrencyId"))), refVal_setFreightCurrencyId );
        setFreightCurrencyId(refVal_setFreightCurrencyId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("totalGrossWeightKg"))))
    {
        double refVal_setTotalGrossWeightKg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("totalGrossWeightKg"))), refVal_setTotalGrossWeightKg );
        setTotalGrossWeightKg(refVal_setTotalGrossWeightKg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("totalPackages"))))
    {
        int32_t refVal_setTotalPackages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("totalPackages"))), refVal_setTotalPackages );
        setTotalPackages(refVal_setTotalPackages);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("totalVolumeM3"))))
    {
        double refVal_setTotalVolumeM3;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("totalVolumeM3"))), refVal_setTotalVolumeM3 );
        setTotalVolumeM3(refVal_setTotalVolumeM3);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("customsFormalities"))))
    {
        utility::string_t refVal_setCustomsFormalities;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("customsFormalities"))), refVal_setCustomsFormalities );
        setCustomsFormalities(refVal_setCustomsFormalities);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("specialInstructions"))))
    {
        utility::string_t refVal_setSpecialInstructions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("specialInstructions"))), refVal_setSpecialInstructions );
        setSpecialInstructions(refVal_setSpecialInstructions);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("remarks"))))
    {
        utility::string_t refVal_setRemarks;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("remarks"))), refVal_setRemarks );
        setRemarks(refVal_setRemarks);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("senderSignedDate"))))
    {
        utility::datetime refVal_setSenderSignedDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("senderSignedDate"))), refVal_setSenderSignedDate );
        setSenderSignedDate(refVal_setSenderSignedDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("carrierSignedDate"))))
    {
        utility::datetime refVal_setCarrierSignedDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("carrierSignedDate"))), refVal_setCarrierSignedDate );
        setCarrierSignedDate(refVal_setCarrierSignedDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("shipmentId"))))
    {
        utility::string_t refVal_setShipmentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("shipmentId"))), refVal_setShipmentId );
        setShipmentId(refVal_setShipmentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("enrollmentId"))))
    {
        utility::string_t refVal_setEnrollmentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("enrollmentId"))), refVal_setEnrollmentId );
        setEnrollmentId(refVal_setEnrollmentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("lines"))))
    {
        std::vector<std::shared_ptr<WaybillLineDto>> refVal_setLines;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("lines"))), refVal_setLines );
        setLines(refVal_setLines);
    }
    return ok;
}

utility::string_t RailWaybillDto::getId() const
{
    return m_Id;
}

void RailWaybillDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool RailWaybillDto::idIsSet() const
{
    return m_IdIsSet;
}

void RailWaybillDto::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime RailWaybillDto::getTimestamp() const
{
    return m_Timestamp;
}

void RailWaybillDto::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool RailWaybillDto::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void RailWaybillDto::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
utility::string_t RailWaybillDto::getDocumentNumber() const
{
    return m_DocumentNumber;
}

void RailWaybillDto::setDocumentNumber(const utility::string_t& value)
{
    m_DocumentNumber = value;
    m_DocumentNumberIsSet = true;
}

bool RailWaybillDto::documentNumberIsSet() const
{
    return m_DocumentNumberIsSet;
}

void RailWaybillDto::unsetDocumentNumber()
{
    m_DocumentNumberIsSet = false;
}
utility::string_t RailWaybillDto::getStatus() const
{
    return m_Status;
}

void RailWaybillDto::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool RailWaybillDto::statusIsSet() const
{
    return m_StatusIsSet;
}

void RailWaybillDto::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t RailWaybillDto::getShipperContactId() const
{
    return m_ShipperContactId;
}

void RailWaybillDto::setShipperContactId(const utility::string_t& value)
{
    m_ShipperContactId = value;
    m_ShipperContactIdIsSet = true;
}

bool RailWaybillDto::shipperContactIdIsSet() const
{
    return m_ShipperContactIdIsSet;
}

void RailWaybillDto::unsetShipperContactId()
{
    m_ShipperContactIdIsSet = false;
}
utility::string_t RailWaybillDto::getConsigneeContactId() const
{
    return m_ConsigneeContactId;
}

void RailWaybillDto::setConsigneeContactId(const utility::string_t& value)
{
    m_ConsigneeContactId = value;
    m_ConsigneeContactIdIsSet = true;
}

bool RailWaybillDto::consigneeContactIdIsSet() const
{
    return m_ConsigneeContactIdIsSet;
}

void RailWaybillDto::unsetConsigneeContactId()
{
    m_ConsigneeContactIdIsSet = false;
}
utility::string_t RailWaybillDto::getCarrierId() const
{
    return m_CarrierId;
}

void RailWaybillDto::setCarrierId(const utility::string_t& value)
{
    m_CarrierId = value;
    m_CarrierIdIsSet = true;
}

bool RailWaybillDto::carrierIdIsSet() const
{
    return m_CarrierIdIsSet;
}

void RailWaybillDto::unsetCarrierId()
{
    m_CarrierIdIsSet = false;
}
utility::string_t RailWaybillDto::getRailOperatorName() const
{
    return m_RailOperatorName;
}

void RailWaybillDto::setRailOperatorName(const utility::string_t& value)
{
    m_RailOperatorName = value;
    m_RailOperatorNameIsSet = true;
}

bool RailWaybillDto::railOperatorNameIsSet() const
{
    return m_RailOperatorNameIsSet;
}

void RailWaybillDto::unsetRailOperatorName()
{
    m_RailOperatorNameIsSet = false;
}
utility::string_t RailWaybillDto::getStationOfDeparture() const
{
    return m_StationOfDeparture;
}

void RailWaybillDto::setStationOfDeparture(const utility::string_t& value)
{
    m_StationOfDeparture = value;
    m_StationOfDepartureIsSet = true;
}

bool RailWaybillDto::stationOfDepartureIsSet() const
{
    return m_StationOfDepartureIsSet;
}

void RailWaybillDto::unsetStationOfDeparture()
{
    m_StationOfDepartureIsSet = false;
}
utility::string_t RailWaybillDto::getStationOfDepartureCode() const
{
    return m_StationOfDepartureCode;
}

void RailWaybillDto::setStationOfDepartureCode(const utility::string_t& value)
{
    m_StationOfDepartureCode = value;
    m_StationOfDepartureCodeIsSet = true;
}

bool RailWaybillDto::stationOfDepartureCodeIsSet() const
{
    return m_StationOfDepartureCodeIsSet;
}

void RailWaybillDto::unsetStationOfDepartureCode()
{
    m_StationOfDepartureCodeIsSet = false;
}
utility::string_t RailWaybillDto::getStationOfDestination() const
{
    return m_StationOfDestination;
}

void RailWaybillDto::setStationOfDestination(const utility::string_t& value)
{
    m_StationOfDestination = value;
    m_StationOfDestinationIsSet = true;
}

bool RailWaybillDto::stationOfDestinationIsSet() const
{
    return m_StationOfDestinationIsSet;
}

void RailWaybillDto::unsetStationOfDestination()
{
    m_StationOfDestinationIsSet = false;
}
utility::string_t RailWaybillDto::getStationOfDestinationCode() const
{
    return m_StationOfDestinationCode;
}

void RailWaybillDto::setStationOfDestinationCode(const utility::string_t& value)
{
    m_StationOfDestinationCode = value;
    m_StationOfDestinationCodeIsSet = true;
}

bool RailWaybillDto::stationOfDestinationCodeIsSet() const
{
    return m_StationOfDestinationCodeIsSet;
}

void RailWaybillDto::unsetStationOfDestinationCode()
{
    m_StationOfDestinationCodeIsSet = false;
}
utility::string_t RailWaybillDto::getPrescribedRoute() const
{
    return m_PrescribedRoute;
}

void RailWaybillDto::setPrescribedRoute(const utility::string_t& value)
{
    m_PrescribedRoute = value;
    m_PrescribedRouteIsSet = true;
}

bool RailWaybillDto::prescribedRouteIsSet() const
{
    return m_PrescribedRouteIsSet;
}

void RailWaybillDto::unsetPrescribedRoute()
{
    m_PrescribedRouteIsSet = false;
}
utility::string_t RailWaybillDto::getWagonNumbers() const
{
    return m_WagonNumbers;
}

void RailWaybillDto::setWagonNumbers(const utility::string_t& value)
{
    m_WagonNumbers = value;
    m_WagonNumbersIsSet = true;
}

bool RailWaybillDto::wagonNumbersIsSet() const
{
    return m_WagonNumbersIsSet;
}

void RailWaybillDto::unsetWagonNumbers()
{
    m_WagonNumbersIsSet = false;
}
utility::datetime RailWaybillDto::getDateOfAcceptance() const
{
    return m_DateOfAcceptance;
}

void RailWaybillDto::setDateOfAcceptance(const utility::datetime& value)
{
    m_DateOfAcceptance = value;
    m_DateOfAcceptanceIsSet = true;
}

bool RailWaybillDto::dateOfAcceptanceIsSet() const
{
    return m_DateOfAcceptanceIsSet;
}

void RailWaybillDto::unsetDateOfAcceptance()
{
    m_DateOfAcceptanceIsSet = false;
}
utility::datetime RailWaybillDto::getDateOfDelivery() const
{
    return m_DateOfDelivery;
}

void RailWaybillDto::setDateOfDelivery(const utility::datetime& value)
{
    m_DateOfDelivery = value;
    m_DateOfDeliveryIsSet = true;
}

bool RailWaybillDto::dateOfDeliveryIsSet() const
{
    return m_DateOfDeliveryIsSet;
}

void RailWaybillDto::unsetDateOfDelivery()
{
    m_DateOfDeliveryIsSet = false;
}
utility::string_t RailWaybillDto::getFreightTerms() const
{
    return m_FreightTerms;
}

void RailWaybillDto::setFreightTerms(const utility::string_t& value)
{
    m_FreightTerms = value;
    m_FreightTermsIsSet = true;
}

bool RailWaybillDto::freightTermsIsSet() const
{
    return m_FreightTermsIsSet;
}

void RailWaybillDto::unsetFreightTerms()
{
    m_FreightTermsIsSet = false;
}
double RailWaybillDto::getFreightAmount() const
{
    return m_FreightAmount;
}

void RailWaybillDto::setFreightAmount(double value)
{
    m_FreightAmount = value;
    m_FreightAmountIsSet = true;
}

bool RailWaybillDto::freightAmountIsSet() const
{
    return m_FreightAmountIsSet;
}

void RailWaybillDto::unsetFreightAmount()
{
    m_FreightAmountIsSet = false;
}
utility::string_t RailWaybillDto::getFreightCurrencyId() const
{
    return m_FreightCurrencyId;
}

void RailWaybillDto::setFreightCurrencyId(const utility::string_t& value)
{
    m_FreightCurrencyId = value;
    m_FreightCurrencyIdIsSet = true;
}

bool RailWaybillDto::freightCurrencyIdIsSet() const
{
    return m_FreightCurrencyIdIsSet;
}

void RailWaybillDto::unsetFreightCurrencyId()
{
    m_FreightCurrencyIdIsSet = false;
}
double RailWaybillDto::getTotalGrossWeightKg() const
{
    return m_TotalGrossWeightKg;
}

void RailWaybillDto::setTotalGrossWeightKg(double value)
{
    m_TotalGrossWeightKg = value;
    m_TotalGrossWeightKgIsSet = true;
}

bool RailWaybillDto::totalGrossWeightKgIsSet() const
{
    return m_TotalGrossWeightKgIsSet;
}

void RailWaybillDto::unsetTotalGrossWeightKg()
{
    m_TotalGrossWeightKgIsSet = false;
}
int32_t RailWaybillDto::getTotalPackages() const
{
    return m_TotalPackages;
}

void RailWaybillDto::setTotalPackages(int32_t value)
{
    m_TotalPackages = value;
    m_TotalPackagesIsSet = true;
}

bool RailWaybillDto::totalPackagesIsSet() const
{
    return m_TotalPackagesIsSet;
}

void RailWaybillDto::unsetTotalPackages()
{
    m_TotalPackagesIsSet = false;
}
double RailWaybillDto::getTotalVolumeM3() const
{
    return m_TotalVolumeM3;
}

void RailWaybillDto::setTotalVolumeM3(double value)
{
    m_TotalVolumeM3 = value;
    m_TotalVolumeM3IsSet = true;
}

bool RailWaybillDto::totalVolumeM3IsSet() const
{
    return m_TotalVolumeM3IsSet;
}

void RailWaybillDto::unsetTotalVolumeM3()
{
    m_TotalVolumeM3IsSet = false;
}
utility::string_t RailWaybillDto::getCustomsFormalities() const
{
    return m_CustomsFormalities;
}

void RailWaybillDto::setCustomsFormalities(const utility::string_t& value)
{
    m_CustomsFormalities = value;
    m_CustomsFormalitiesIsSet = true;
}

bool RailWaybillDto::customsFormalitiesIsSet() const
{
    return m_CustomsFormalitiesIsSet;
}

void RailWaybillDto::unsetCustomsFormalities()
{
    m_CustomsFormalitiesIsSet = false;
}
utility::string_t RailWaybillDto::getSpecialInstructions() const
{
    return m_SpecialInstructions;
}

void RailWaybillDto::setSpecialInstructions(const utility::string_t& value)
{
    m_SpecialInstructions = value;
    m_SpecialInstructionsIsSet = true;
}

bool RailWaybillDto::specialInstructionsIsSet() const
{
    return m_SpecialInstructionsIsSet;
}

void RailWaybillDto::unsetSpecialInstructions()
{
    m_SpecialInstructionsIsSet = false;
}
utility::string_t RailWaybillDto::getRemarks() const
{
    return m_Remarks;
}

void RailWaybillDto::setRemarks(const utility::string_t& value)
{
    m_Remarks = value;
    m_RemarksIsSet = true;
}

bool RailWaybillDto::remarksIsSet() const
{
    return m_RemarksIsSet;
}

void RailWaybillDto::unsetRemarks()
{
    m_RemarksIsSet = false;
}
utility::datetime RailWaybillDto::getSenderSignedDate() const
{
    return m_SenderSignedDate;
}

void RailWaybillDto::setSenderSignedDate(const utility::datetime& value)
{
    m_SenderSignedDate = value;
    m_SenderSignedDateIsSet = true;
}

bool RailWaybillDto::senderSignedDateIsSet() const
{
    return m_SenderSignedDateIsSet;
}

void RailWaybillDto::unsetSenderSignedDate()
{
    m_SenderSignedDateIsSet = false;
}
utility::datetime RailWaybillDto::getCarrierSignedDate() const
{
    return m_CarrierSignedDate;
}

void RailWaybillDto::setCarrierSignedDate(const utility::datetime& value)
{
    m_CarrierSignedDate = value;
    m_CarrierSignedDateIsSet = true;
}

bool RailWaybillDto::carrierSignedDateIsSet() const
{
    return m_CarrierSignedDateIsSet;
}

void RailWaybillDto::unsetCarrierSignedDate()
{
    m_CarrierSignedDateIsSet = false;
}
utility::string_t RailWaybillDto::getShipmentId() const
{
    return m_ShipmentId;
}

void RailWaybillDto::setShipmentId(const utility::string_t& value)
{
    m_ShipmentId = value;
    m_ShipmentIdIsSet = true;
}

bool RailWaybillDto::shipmentIdIsSet() const
{
    return m_ShipmentIdIsSet;
}

void RailWaybillDto::unsetShipmentId()
{
    m_ShipmentIdIsSet = false;
}
utility::string_t RailWaybillDto::getTenantId() const
{
    return m_TenantId;
}

void RailWaybillDto::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool RailWaybillDto::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void RailWaybillDto::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
utility::string_t RailWaybillDto::getEnrollmentId() const
{
    return m_EnrollmentId;
}

void RailWaybillDto::setEnrollmentId(const utility::string_t& value)
{
    m_EnrollmentId = value;
    m_EnrollmentIdIsSet = true;
}

bool RailWaybillDto::enrollmentIdIsSet() const
{
    return m_EnrollmentIdIsSet;
}

void RailWaybillDto::unsetEnrollmentId()
{
    m_EnrollmentIdIsSet = false;
}
std::vector<std::shared_ptr<WaybillLineDto>>& RailWaybillDto::getLines()
{
    return m_Lines;
}

void RailWaybillDto::setLines(const std::vector<std::shared_ptr<WaybillLineDto>>& value)
{
    m_Lines = value;
    m_LinesIsSet = true;
}

bool RailWaybillDto::linesIsSet() const
{
    return m_LinesIsSet;
}

void RailWaybillDto::unsetLines()
{
    m_LinesIsSet = false;
}
}
}
}
}


