/**
 * InvoicingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InvoiceReferenceUpdateDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_InvoiceReferenceUpdateDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_InvoiceReferenceUpdateDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  InvoiceReferenceUpdateDto
    : public ModelBase
{
public:
    InvoiceReferenceUpdateDto();
    virtual ~InvoiceReferenceUpdateDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// InvoiceReferenceUpdateDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getReferencedInvoiceId() const;
    bool referencedInvoiceIdIsSet() const;
    void unsetReferencedInvoiceId();

    void setReferencedInvoiceId(const utility::string_t& value);


protected:
    utility::string_t m_ReferencedInvoiceId;
    bool m_ReferencedInvoiceIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_InvoiceReferenceUpdateDto_H_ */
