/**
 * HrmsService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/GigApplicationDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



GigApplicationDto::GigApplicationDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_AcceptedTimestamp = utility::datetime();
    m_AcceptedTimestampIsSet = false;
    m_Accepted = false;
    m_AcceptedIsSet = false;
    m_Proposal = utility::conversions::to_string_t("");
    m_ProposalIsSet = false;
    m_Cost = 0.0;
    m_CostIsSet = false;
    m_GigId = utility::conversions::to_string_t("");
    m_GigIdIsSet = false;
    m_CurrencyId = utility::conversions::to_string_t("");
    m_CurrencyIdIsSet = false;
    m_CurriculumId = utility::conversions::to_string_t("");
    m_CurriculumIdIsSet = false;
    m_CurriculumCoverId = utility::conversions::to_string_t("");
    m_CurriculumCoverIdIsSet = false;
    m_JobApplicantProfileId = utility::conversions::to_string_t("");
    m_JobApplicantProfileIdIsSet = false;
}

GigApplicationDto::~GigApplicationDto()
{
}

void GigApplicationDto::validate()
{
    // TODO: implement validation
}

web::json::value GigApplicationDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_AcceptedTimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("acceptedTimestamp"))] = ModelBase::toJson(m_AcceptedTimestamp);
    }
    if(m_AcceptedIsSet)
    {
        val[utility::conversions::to_string_t(U("accepted"))] = ModelBase::toJson(m_Accepted);
    }
    if(m_ProposalIsSet)
    {
        val[utility::conversions::to_string_t(U("proposal"))] = ModelBase::toJson(m_Proposal);
    }
    if(m_CostIsSet)
    {
        val[utility::conversions::to_string_t(U("cost"))] = ModelBase::toJson(m_Cost);
    }
    if(m_GigIdIsSet)
    {
        val[utility::conversions::to_string_t(U("gigId"))] = ModelBase::toJson(m_GigId);
    }
    if(m_CurrencyIdIsSet)
    {
        val[utility::conversions::to_string_t(U("currencyId"))] = ModelBase::toJson(m_CurrencyId);
    }
    if(m_CurriculumIdIsSet)
    {
        val[utility::conversions::to_string_t(U("curriculumId"))] = ModelBase::toJson(m_CurriculumId);
    }
    if(m_CurriculumCoverIdIsSet)
    {
        val[utility::conversions::to_string_t(U("curriculumCoverId"))] = ModelBase::toJson(m_CurriculumCoverId);
    }
    if(m_JobApplicantProfileIdIsSet)
    {
        val[utility::conversions::to_string_t(U("jobApplicantProfileId"))] = ModelBase::toJson(m_JobApplicantProfileId);
    }

    return val;
}

bool GigApplicationDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("acceptedTimestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("acceptedTimestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setAcceptedTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAcceptedTimestamp);
            setAcceptedTimestamp(refVal_setAcceptedTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("accepted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("accepted")));
        if(!fieldValue.is_null())
        {
            bool refVal_setAccepted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccepted);
            setAccepted(refVal_setAccepted);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("proposal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("proposal")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProposal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProposal);
            setProposal(refVal_setProposal);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("cost"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("cost")));
        if(!fieldValue.is_null())
        {
            double refVal_setCost;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCost);
            setCost(refVal_setCost);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gigId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gigId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGigId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGigId);
            setGigId(refVal_setGigId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("currencyId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("currencyId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCurrencyId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurrencyId);
            setCurrencyId(refVal_setCurrencyId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("curriculumId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("curriculumId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCurriculumId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurriculumId);
            setCurriculumId(refVal_setCurriculumId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("curriculumCoverId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("curriculumCoverId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCurriculumCoverId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurriculumCoverId);
            setCurriculumCoverId(refVal_setCurriculumCoverId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("jobApplicantProfileId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("jobApplicantProfileId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setJobApplicantProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setJobApplicantProfileId);
            setJobApplicantProfileId(refVal_setJobApplicantProfileId);
        }
    }
    return ok;
}

void GigApplicationDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_AcceptedTimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("acceptedTimestamp")), m_AcceptedTimestamp));
    }
    if(m_AcceptedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("accepted")), m_Accepted));
    }
    if(m_ProposalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("proposal")), m_Proposal));
    }
    if(m_CostIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("cost")), m_Cost));
    }
    if(m_GigIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gigId")), m_GigId));
    }
    if(m_CurrencyIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("currencyId")), m_CurrencyId));
    }
    if(m_CurriculumIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("curriculumId")), m_CurriculumId));
    }
    if(m_CurriculumCoverIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("curriculumCoverId")), m_CurriculumCoverId));
    }
    if(m_JobApplicantProfileIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("jobApplicantProfileId")), m_JobApplicantProfileId));
    }
}

bool GigApplicationDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("acceptedTimestamp"))))
    {
        utility::datetime refVal_setAcceptedTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("acceptedTimestamp"))), refVal_setAcceptedTimestamp );
        setAcceptedTimestamp(refVal_setAcceptedTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("accepted"))))
    {
        bool refVal_setAccepted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("accepted"))), refVal_setAccepted );
        setAccepted(refVal_setAccepted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("proposal"))))
    {
        utility::string_t refVal_setProposal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("proposal"))), refVal_setProposal );
        setProposal(refVal_setProposal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("cost"))))
    {
        double refVal_setCost;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("cost"))), refVal_setCost );
        setCost(refVal_setCost);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gigId"))))
    {
        utility::string_t refVal_setGigId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gigId"))), refVal_setGigId );
        setGigId(refVal_setGigId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("currencyId"))))
    {
        utility::string_t refVal_setCurrencyId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("currencyId"))), refVal_setCurrencyId );
        setCurrencyId(refVal_setCurrencyId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("curriculumId"))))
    {
        utility::string_t refVal_setCurriculumId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("curriculumId"))), refVal_setCurriculumId );
        setCurriculumId(refVal_setCurriculumId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("curriculumCoverId"))))
    {
        utility::string_t refVal_setCurriculumCoverId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("curriculumCoverId"))), refVal_setCurriculumCoverId );
        setCurriculumCoverId(refVal_setCurriculumCoverId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("jobApplicantProfileId"))))
    {
        utility::string_t refVal_setJobApplicantProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("jobApplicantProfileId"))), refVal_setJobApplicantProfileId );
        setJobApplicantProfileId(refVal_setJobApplicantProfileId);
    }
    return ok;
}

utility::string_t GigApplicationDto::getId() const
{
    return m_Id;
}

void GigApplicationDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool GigApplicationDto::idIsSet() const
{
    return m_IdIsSet;
}

void GigApplicationDto::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime GigApplicationDto::getTimestamp() const
{
    return m_Timestamp;
}

void GigApplicationDto::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool GigApplicationDto::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void GigApplicationDto::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
utility::datetime GigApplicationDto::getAcceptedTimestamp() const
{
    return m_AcceptedTimestamp;
}

void GigApplicationDto::setAcceptedTimestamp(const utility::datetime& value)
{
    m_AcceptedTimestamp = value;
    m_AcceptedTimestampIsSet = true;
}

bool GigApplicationDto::acceptedTimestampIsSet() const
{
    return m_AcceptedTimestampIsSet;
}

void GigApplicationDto::unsetAcceptedTimestamp()
{
    m_AcceptedTimestampIsSet = false;
}
bool GigApplicationDto::isAccepted() const
{
    return m_Accepted;
}

void GigApplicationDto::setAccepted(bool value)
{
    m_Accepted = value;
    m_AcceptedIsSet = true;
}

bool GigApplicationDto::acceptedIsSet() const
{
    return m_AcceptedIsSet;
}

void GigApplicationDto::unsetAccepted()
{
    m_AcceptedIsSet = false;
}
utility::string_t GigApplicationDto::getProposal() const
{
    return m_Proposal;
}

void GigApplicationDto::setProposal(const utility::string_t& value)
{
    m_Proposal = value;
    m_ProposalIsSet = true;
}

bool GigApplicationDto::proposalIsSet() const
{
    return m_ProposalIsSet;
}

void GigApplicationDto::unsetProposal()
{
    m_ProposalIsSet = false;
}
double GigApplicationDto::getCost() const
{
    return m_Cost;
}

void GigApplicationDto::setCost(double value)
{
    m_Cost = value;
    m_CostIsSet = true;
}

bool GigApplicationDto::costIsSet() const
{
    return m_CostIsSet;
}

void GigApplicationDto::unsetCost()
{
    m_CostIsSet = false;
}
utility::string_t GigApplicationDto::getGigId() const
{
    return m_GigId;
}

void GigApplicationDto::setGigId(const utility::string_t& value)
{
    m_GigId = value;
    m_GigIdIsSet = true;
}

bool GigApplicationDto::gigIdIsSet() const
{
    return m_GigIdIsSet;
}

void GigApplicationDto::unsetGigId()
{
    m_GigIdIsSet = false;
}
utility::string_t GigApplicationDto::getCurrencyId() const
{
    return m_CurrencyId;
}

void GigApplicationDto::setCurrencyId(const utility::string_t& value)
{
    m_CurrencyId = value;
    m_CurrencyIdIsSet = true;
}

bool GigApplicationDto::currencyIdIsSet() const
{
    return m_CurrencyIdIsSet;
}

void GigApplicationDto::unsetCurrencyId()
{
    m_CurrencyIdIsSet = false;
}
utility::string_t GigApplicationDto::getCurriculumId() const
{
    return m_CurriculumId;
}

void GigApplicationDto::setCurriculumId(const utility::string_t& value)
{
    m_CurriculumId = value;
    m_CurriculumIdIsSet = true;
}

bool GigApplicationDto::curriculumIdIsSet() const
{
    return m_CurriculumIdIsSet;
}

void GigApplicationDto::unsetCurriculumId()
{
    m_CurriculumIdIsSet = false;
}
utility::string_t GigApplicationDto::getCurriculumCoverId() const
{
    return m_CurriculumCoverId;
}

void GigApplicationDto::setCurriculumCoverId(const utility::string_t& value)
{
    m_CurriculumCoverId = value;
    m_CurriculumCoverIdIsSet = true;
}

bool GigApplicationDto::curriculumCoverIdIsSet() const
{
    return m_CurriculumCoverIdIsSet;
}

void GigApplicationDto::unsetCurriculumCoverId()
{
    m_CurriculumCoverIdIsSet = false;
}
utility::string_t GigApplicationDto::getJobApplicantProfileId() const
{
    return m_JobApplicantProfileId;
}

void GigApplicationDto::setJobApplicantProfileId(const utility::string_t& value)
{
    m_JobApplicantProfileId = value;
    m_JobApplicantProfileIdIsSet = true;
}

bool GigApplicationDto::jobApplicantProfileIdIsSet() const
{
    return m_JobApplicantProfileIdIsSet;
}

void GigApplicationDto::unsetJobApplicantProfileId()
{
    m_JobApplicantProfileIdIsSet = false;
}
}
}
}
}


