/**
 * LearningService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/StudentProfileDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



StudentProfileDto::StudentProfileDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_About = utility::conversions::to_string_t("");
    m_AboutIsSet = false;
    m_Verified = false;
    m_VerifiedIsSet = false;
    m_Submitted = false;
    m_SubmittedIsSet = false;
    m_AvatarUrl = utility::conversions::to_string_t("");
    m_AvatarUrlIsSet = false;
    m_QualifiedName = utility::conversions::to_string_t("");
    m_QualifiedNameIsSet = false;
    m_VerificationTimestamp = utility::datetime();
    m_VerificationTimestampIsSet = false;
    m_Data = utility::conversions::to_string_t("");
    m_DataIsSet = false;
    m_DataLabel = utility::conversions::to_string_t("");
    m_DataLabelIsSet = false;
    m_Data1 = utility::conversions::to_string_t("");
    m_Data1IsSet = false;
    m_Data1Label = utility::conversions::to_string_t("");
    m_Data1LabelIsSet = false;
    m_Data2 = utility::conversions::to_string_t("");
    m_Data2IsSet = false;
    m_Data2Label = utility::conversions::to_string_t("");
    m_Data2LabelIsSet = false;
    m_Data3 = utility::conversions::to_string_t("");
    m_Data3IsSet = false;
    m_Data3Label = utility::conversions::to_string_t("");
    m_Data3LabelIsSet = false;
    m_Data4 = utility::conversions::to_string_t("");
    m_Data4IsSet = false;
    m_Data4Label = utility::conversions::to_string_t("");
    m_Data4LabelIsSet = false;
    m_Data5 = utility::conversions::to_string_t("");
    m_Data5IsSet = false;
    m_Data5Label = utility::conversions::to_string_t("");
    m_Data5LabelIsSet = false;
    m_Data6 = utility::conversions::to_string_t("");
    m_Data6IsSet = false;
    m_Data6Label = utility::conversions::to_string_t("");
    m_Data6LabelIsSet = false;
    m_Data7 = utility::conversions::to_string_t("");
    m_Data7IsSet = false;
    m_Data7Label = utility::conversions::to_string_t("");
    m_Data7LabelIsSet = false;
    m_Data8 = utility::conversions::to_string_t("");
    m_Data8IsSet = false;
    m_Data8Label = utility::conversions::to_string_t("");
    m_Data8LabelIsSet = false;
    m_Data9 = utility::conversions::to_string_t("");
    m_Data9IsSet = false;
    m_Data9Label = utility::conversions::to_string_t("");
    m_Data9LabelIsSet = false;
    m_BusinessID = utility::conversions::to_string_t("");
    m_BusinessIDIsSet = false;
    m_ContactID = utility::conversions::to_string_t("");
    m_ContactIDIsSet = false;
    m_BusinessProfileRecordID = utility::conversions::to_string_t("");
    m_BusinessProfileRecordIDIsSet = false;
}

StudentProfileDto::~StudentProfileDto()
{
}

void StudentProfileDto::validate()
{
    // TODO: implement validation
}

web::json::value StudentProfileDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_AboutIsSet)
    {
        val[utility::conversions::to_string_t(U("about"))] = ModelBase::toJson(m_About);
    }
    if(m_VerifiedIsSet)
    {
        val[utility::conversions::to_string_t(U("verified"))] = ModelBase::toJson(m_Verified);
    }
    if(m_SubmittedIsSet)
    {
        val[utility::conversions::to_string_t(U("submitted"))] = ModelBase::toJson(m_Submitted);
    }
    if(m_AvatarUrlIsSet)
    {
        val[utility::conversions::to_string_t(U("avatarUrl"))] = ModelBase::toJson(m_AvatarUrl);
    }
    if(m_QualifiedNameIsSet)
    {
        val[utility::conversions::to_string_t(U("qualifiedName"))] = ModelBase::toJson(m_QualifiedName);
    }
    if(m_VerificationTimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("verificationTimestamp"))] = ModelBase::toJson(m_VerificationTimestamp);
    }
    if(m_DataIsSet)
    {
        val[utility::conversions::to_string_t(U("data"))] = ModelBase::toJson(m_Data);
    }
    if(m_DataLabelIsSet)
    {
        val[utility::conversions::to_string_t(U("dataLabel"))] = ModelBase::toJson(m_DataLabel);
    }
    if(m_Data1IsSet)
    {
        val[utility::conversions::to_string_t(U("data1"))] = ModelBase::toJson(m_Data1);
    }
    if(m_Data1LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data1Label"))] = ModelBase::toJson(m_Data1Label);
    }
    if(m_Data2IsSet)
    {
        val[utility::conversions::to_string_t(U("data2"))] = ModelBase::toJson(m_Data2);
    }
    if(m_Data2LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data2Label"))] = ModelBase::toJson(m_Data2Label);
    }
    if(m_Data3IsSet)
    {
        val[utility::conversions::to_string_t(U("data3"))] = ModelBase::toJson(m_Data3);
    }
    if(m_Data3LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data3Label"))] = ModelBase::toJson(m_Data3Label);
    }
    if(m_Data4IsSet)
    {
        val[utility::conversions::to_string_t(U("data4"))] = ModelBase::toJson(m_Data4);
    }
    if(m_Data4LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data4Label"))] = ModelBase::toJson(m_Data4Label);
    }
    if(m_Data5IsSet)
    {
        val[utility::conversions::to_string_t(U("data5"))] = ModelBase::toJson(m_Data5);
    }
    if(m_Data5LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data5Label"))] = ModelBase::toJson(m_Data5Label);
    }
    if(m_Data6IsSet)
    {
        val[utility::conversions::to_string_t(U("data6"))] = ModelBase::toJson(m_Data6);
    }
    if(m_Data6LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data6Label"))] = ModelBase::toJson(m_Data6Label);
    }
    if(m_Data7IsSet)
    {
        val[utility::conversions::to_string_t(U("data7"))] = ModelBase::toJson(m_Data7);
    }
    if(m_Data7LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data7Label"))] = ModelBase::toJson(m_Data7Label);
    }
    if(m_Data8IsSet)
    {
        val[utility::conversions::to_string_t(U("data8"))] = ModelBase::toJson(m_Data8);
    }
    if(m_Data8LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data8Label"))] = ModelBase::toJson(m_Data8Label);
    }
    if(m_Data9IsSet)
    {
        val[utility::conversions::to_string_t(U("data9"))] = ModelBase::toJson(m_Data9);
    }
    if(m_Data9LabelIsSet)
    {
        val[utility::conversions::to_string_t(U("data9Label"))] = ModelBase::toJson(m_Data9Label);
    }
    if(m_BusinessIDIsSet)
    {
        val[utility::conversions::to_string_t(U("businessID"))] = ModelBase::toJson(m_BusinessID);
    }
    if(m_ContactIDIsSet)
    {
        val[utility::conversions::to_string_t(U("contactID"))] = ModelBase::toJson(m_ContactID);
    }
    if(m_BusinessProfileRecordIDIsSet)
    {
        val[utility::conversions::to_string_t(U("businessProfileRecordID"))] = ModelBase::toJson(m_BusinessProfileRecordID);
    }

    return val;
}

bool StudentProfileDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("about"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("about")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAbout;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAbout);
            setAbout(refVal_setAbout);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("verified"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("verified")));
        if(!fieldValue.is_null())
        {
            bool refVal_setVerified;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerified);
            setVerified(refVal_setVerified);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("submitted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("submitted")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSubmitted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubmitted);
            setSubmitted(refVal_setSubmitted);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("avatarUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("avatarUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatarUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatarUrl);
            setAvatarUrl(refVal_setAvatarUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("qualifiedName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("qualifiedName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQualifiedName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQualifiedName);
            setQualifiedName(refVal_setQualifiedName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("verificationTimestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("verificationTimestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setVerificationTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerificationTimestamp);
            setVerificationTimestamp(refVal_setVerificationTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData);
            setData(refVal_setData);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("dataLabel"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("dataLabel")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDataLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDataLabel);
            setDataLabel(refVal_setDataLabel);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data1"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data1")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData1;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData1);
            setData1(refVal_setData1);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data1Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data1Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData1Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData1Label);
            setData1Label(refVal_setData1Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data2"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data2")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData2;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData2);
            setData2(refVal_setData2);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data2Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data2Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData2Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData2Label);
            setData2Label(refVal_setData2Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data3"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data3")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData3;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData3);
            setData3(refVal_setData3);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data3Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data3Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData3Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData3Label);
            setData3Label(refVal_setData3Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data4"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data4")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData4;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData4);
            setData4(refVal_setData4);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data4Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data4Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData4Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData4Label);
            setData4Label(refVal_setData4Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data5"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data5")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData5;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData5);
            setData5(refVal_setData5);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data5Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data5Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData5Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData5Label);
            setData5Label(refVal_setData5Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data6"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data6")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData6;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData6);
            setData6(refVal_setData6);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data6Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data6Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData6Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData6Label);
            setData6Label(refVal_setData6Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data7"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data7")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData7;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData7);
            setData7(refVal_setData7);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data7Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data7Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData7Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData7Label);
            setData7Label(refVal_setData7Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data8"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data8")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData8;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData8);
            setData8(refVal_setData8);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data8Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data8Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData8Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData8Label);
            setData8Label(refVal_setData8Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data9"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data9")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData9;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData9);
            setData9(refVal_setData9);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data9Label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data9Label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData9Label;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData9Label);
            setData9Label(refVal_setData9Label);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("businessID"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("businessID")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBusinessID;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBusinessID);
            setBusinessID(refVal_setBusinessID);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("contactID"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("contactID")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContactID;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContactID);
            setContactID(refVal_setContactID);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("businessProfileRecordID"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("businessProfileRecordID")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBusinessProfileRecordID;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBusinessProfileRecordID);
            setBusinessProfileRecordID(refVal_setBusinessProfileRecordID);
        }
    }
    return ok;
}

void StudentProfileDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_AboutIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("about")), m_About));
    }
    if(m_VerifiedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("verified")), m_Verified));
    }
    if(m_SubmittedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("submitted")), m_Submitted));
    }
    if(m_AvatarUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("avatarUrl")), m_AvatarUrl));
    }
    if(m_QualifiedNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("qualifiedName")), m_QualifiedName));
    }
    if(m_VerificationTimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("verificationTimestamp")), m_VerificationTimestamp));
    }
    if(m_DataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data")), m_Data));
    }
    if(m_DataLabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("dataLabel")), m_DataLabel));
    }
    if(m_Data1IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data1")), m_Data1));
    }
    if(m_Data1LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data1Label")), m_Data1Label));
    }
    if(m_Data2IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data2")), m_Data2));
    }
    if(m_Data2LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data2Label")), m_Data2Label));
    }
    if(m_Data3IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data3")), m_Data3));
    }
    if(m_Data3LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data3Label")), m_Data3Label));
    }
    if(m_Data4IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data4")), m_Data4));
    }
    if(m_Data4LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data4Label")), m_Data4Label));
    }
    if(m_Data5IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data5")), m_Data5));
    }
    if(m_Data5LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data5Label")), m_Data5Label));
    }
    if(m_Data6IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data6")), m_Data6));
    }
    if(m_Data6LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data6Label")), m_Data6Label));
    }
    if(m_Data7IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data7")), m_Data7));
    }
    if(m_Data7LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data7Label")), m_Data7Label));
    }
    if(m_Data8IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data8")), m_Data8));
    }
    if(m_Data8LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data8Label")), m_Data8Label));
    }
    if(m_Data9IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data9")), m_Data9));
    }
    if(m_Data9LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data9Label")), m_Data9Label));
    }
    if(m_BusinessIDIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("businessID")), m_BusinessID));
    }
    if(m_ContactIDIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("contactID")), m_ContactID));
    }
    if(m_BusinessProfileRecordIDIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("businessProfileRecordID")), m_BusinessProfileRecordID));
    }
}

bool StudentProfileDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("about"))))
    {
        utility::string_t refVal_setAbout;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("about"))), refVal_setAbout );
        setAbout(refVal_setAbout);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("verified"))))
    {
        bool refVal_setVerified;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("verified"))), refVal_setVerified );
        setVerified(refVal_setVerified);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("submitted"))))
    {
        bool refVal_setSubmitted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("submitted"))), refVal_setSubmitted );
        setSubmitted(refVal_setSubmitted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("avatarUrl"))))
    {
        utility::string_t refVal_setAvatarUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("avatarUrl"))), refVal_setAvatarUrl );
        setAvatarUrl(refVal_setAvatarUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("qualifiedName"))))
    {
        utility::string_t refVal_setQualifiedName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("qualifiedName"))), refVal_setQualifiedName );
        setQualifiedName(refVal_setQualifiedName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("verificationTimestamp"))))
    {
        utility::datetime refVal_setVerificationTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("verificationTimestamp"))), refVal_setVerificationTimestamp );
        setVerificationTimestamp(refVal_setVerificationTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data"))))
    {
        utility::string_t refVal_setData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data"))), refVal_setData );
        setData(refVal_setData);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("dataLabel"))))
    {
        utility::string_t refVal_setDataLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("dataLabel"))), refVal_setDataLabel );
        setDataLabel(refVal_setDataLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data1"))))
    {
        utility::string_t refVal_setData1;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data1"))), refVal_setData1 );
        setData1(refVal_setData1);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data1Label"))))
    {
        utility::string_t refVal_setData1Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data1Label"))), refVal_setData1Label );
        setData1Label(refVal_setData1Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data2"))))
    {
        utility::string_t refVal_setData2;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data2"))), refVal_setData2 );
        setData2(refVal_setData2);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data2Label"))))
    {
        utility::string_t refVal_setData2Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data2Label"))), refVal_setData2Label );
        setData2Label(refVal_setData2Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data3"))))
    {
        utility::string_t refVal_setData3;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data3"))), refVal_setData3 );
        setData3(refVal_setData3);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data3Label"))))
    {
        utility::string_t refVal_setData3Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data3Label"))), refVal_setData3Label );
        setData3Label(refVal_setData3Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data4"))))
    {
        utility::string_t refVal_setData4;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data4"))), refVal_setData4 );
        setData4(refVal_setData4);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data4Label"))))
    {
        utility::string_t refVal_setData4Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data4Label"))), refVal_setData4Label );
        setData4Label(refVal_setData4Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data5"))))
    {
        utility::string_t refVal_setData5;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data5"))), refVal_setData5 );
        setData5(refVal_setData5);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data5Label"))))
    {
        utility::string_t refVal_setData5Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data5Label"))), refVal_setData5Label );
        setData5Label(refVal_setData5Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data6"))))
    {
        utility::string_t refVal_setData6;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data6"))), refVal_setData6 );
        setData6(refVal_setData6);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data6Label"))))
    {
        utility::string_t refVal_setData6Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data6Label"))), refVal_setData6Label );
        setData6Label(refVal_setData6Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data7"))))
    {
        utility::string_t refVal_setData7;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data7"))), refVal_setData7 );
        setData7(refVal_setData7);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data7Label"))))
    {
        utility::string_t refVal_setData7Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data7Label"))), refVal_setData7Label );
        setData7Label(refVal_setData7Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data8"))))
    {
        utility::string_t refVal_setData8;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data8"))), refVal_setData8 );
        setData8(refVal_setData8);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data8Label"))))
    {
        utility::string_t refVal_setData8Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data8Label"))), refVal_setData8Label );
        setData8Label(refVal_setData8Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data9"))))
    {
        utility::string_t refVal_setData9;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data9"))), refVal_setData9 );
        setData9(refVal_setData9);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data9Label"))))
    {
        utility::string_t refVal_setData9Label;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data9Label"))), refVal_setData9Label );
        setData9Label(refVal_setData9Label);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("businessID"))))
    {
        utility::string_t refVal_setBusinessID;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("businessID"))), refVal_setBusinessID );
        setBusinessID(refVal_setBusinessID);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("contactID"))))
    {
        utility::string_t refVal_setContactID;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("contactID"))), refVal_setContactID );
        setContactID(refVal_setContactID);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("businessProfileRecordID"))))
    {
        utility::string_t refVal_setBusinessProfileRecordID;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("businessProfileRecordID"))), refVal_setBusinessProfileRecordID );
        setBusinessProfileRecordID(refVal_setBusinessProfileRecordID);
    }
    return ok;
}

utility::string_t StudentProfileDto::getId() const
{
    return m_Id;
}

void StudentProfileDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool StudentProfileDto::idIsSet() const
{
    return m_IdIsSet;
}

void StudentProfileDto::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime StudentProfileDto::getTimestamp() const
{
    return m_Timestamp;
}

void StudentProfileDto::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool StudentProfileDto::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void StudentProfileDto::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
utility::string_t StudentProfileDto::getAbout() const
{
    return m_About;
}

void StudentProfileDto::setAbout(const utility::string_t& value)
{
    m_About = value;
    m_AboutIsSet = true;
}

bool StudentProfileDto::aboutIsSet() const
{
    return m_AboutIsSet;
}

void StudentProfileDto::unsetAbout()
{
    m_AboutIsSet = false;
}
bool StudentProfileDto::isVerified() const
{
    return m_Verified;
}

void StudentProfileDto::setVerified(bool value)
{
    m_Verified = value;
    m_VerifiedIsSet = true;
}

bool StudentProfileDto::verifiedIsSet() const
{
    return m_VerifiedIsSet;
}

void StudentProfileDto::unsetVerified()
{
    m_VerifiedIsSet = false;
}
bool StudentProfileDto::isSubmitted() const
{
    return m_Submitted;
}

void StudentProfileDto::setSubmitted(bool value)
{
    m_Submitted = value;
    m_SubmittedIsSet = true;
}

bool StudentProfileDto::submittedIsSet() const
{
    return m_SubmittedIsSet;
}

void StudentProfileDto::unsetSubmitted()
{
    m_SubmittedIsSet = false;
}
utility::string_t StudentProfileDto::getAvatarUrl() const
{
    return m_AvatarUrl;
}

void StudentProfileDto::setAvatarUrl(const utility::string_t& value)
{
    m_AvatarUrl = value;
    m_AvatarUrlIsSet = true;
}

bool StudentProfileDto::avatarUrlIsSet() const
{
    return m_AvatarUrlIsSet;
}

void StudentProfileDto::unsetAvatarUrl()
{
    m_AvatarUrlIsSet = false;
}
utility::string_t StudentProfileDto::getQualifiedName() const
{
    return m_QualifiedName;
}

void StudentProfileDto::setQualifiedName(const utility::string_t& value)
{
    m_QualifiedName = value;
    m_QualifiedNameIsSet = true;
}

bool StudentProfileDto::qualifiedNameIsSet() const
{
    return m_QualifiedNameIsSet;
}

void StudentProfileDto::unsetQualifiedName()
{
    m_QualifiedNameIsSet = false;
}
utility::datetime StudentProfileDto::getVerificationTimestamp() const
{
    return m_VerificationTimestamp;
}

void StudentProfileDto::setVerificationTimestamp(const utility::datetime& value)
{
    m_VerificationTimestamp = value;
    m_VerificationTimestampIsSet = true;
}

bool StudentProfileDto::verificationTimestampIsSet() const
{
    return m_VerificationTimestampIsSet;
}

void StudentProfileDto::unsetVerificationTimestamp()
{
    m_VerificationTimestampIsSet = false;
}
utility::string_t StudentProfileDto::getData() const
{
    return m_Data;
}

void StudentProfileDto::setData(const utility::string_t& value)
{
    m_Data = value;
    m_DataIsSet = true;
}

bool StudentProfileDto::dataIsSet() const
{
    return m_DataIsSet;
}

void StudentProfileDto::unsetData()
{
    m_DataIsSet = false;
}
utility::string_t StudentProfileDto::getDataLabel() const
{
    return m_DataLabel;
}

void StudentProfileDto::setDataLabel(const utility::string_t& value)
{
    m_DataLabel = value;
    m_DataLabelIsSet = true;
}

bool StudentProfileDto::dataLabelIsSet() const
{
    return m_DataLabelIsSet;
}

void StudentProfileDto::unsetDataLabel()
{
    m_DataLabelIsSet = false;
}
utility::string_t StudentProfileDto::getData1() const
{
    return m_Data1;
}

void StudentProfileDto::setData1(const utility::string_t& value)
{
    m_Data1 = value;
    m_Data1IsSet = true;
}

bool StudentProfileDto::data1IsSet() const
{
    return m_Data1IsSet;
}

void StudentProfileDto::unsetData1()
{
    m_Data1IsSet = false;
}
utility::string_t StudentProfileDto::getData1Label() const
{
    return m_Data1Label;
}

void StudentProfileDto::setData1Label(const utility::string_t& value)
{
    m_Data1Label = value;
    m_Data1LabelIsSet = true;
}

bool StudentProfileDto::data1LabelIsSet() const
{
    return m_Data1LabelIsSet;
}

void StudentProfileDto::unsetData1Label()
{
    m_Data1LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData2() const
{
    return m_Data2;
}

void StudentProfileDto::setData2(const utility::string_t& value)
{
    m_Data2 = value;
    m_Data2IsSet = true;
}

bool StudentProfileDto::data2IsSet() const
{
    return m_Data2IsSet;
}

void StudentProfileDto::unsetData2()
{
    m_Data2IsSet = false;
}
utility::string_t StudentProfileDto::getData2Label() const
{
    return m_Data2Label;
}

void StudentProfileDto::setData2Label(const utility::string_t& value)
{
    m_Data2Label = value;
    m_Data2LabelIsSet = true;
}

bool StudentProfileDto::data2LabelIsSet() const
{
    return m_Data2LabelIsSet;
}

void StudentProfileDto::unsetData2Label()
{
    m_Data2LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData3() const
{
    return m_Data3;
}

void StudentProfileDto::setData3(const utility::string_t& value)
{
    m_Data3 = value;
    m_Data3IsSet = true;
}

bool StudentProfileDto::data3IsSet() const
{
    return m_Data3IsSet;
}

void StudentProfileDto::unsetData3()
{
    m_Data3IsSet = false;
}
utility::string_t StudentProfileDto::getData3Label() const
{
    return m_Data3Label;
}

void StudentProfileDto::setData3Label(const utility::string_t& value)
{
    m_Data3Label = value;
    m_Data3LabelIsSet = true;
}

bool StudentProfileDto::data3LabelIsSet() const
{
    return m_Data3LabelIsSet;
}

void StudentProfileDto::unsetData3Label()
{
    m_Data3LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData4() const
{
    return m_Data4;
}

void StudentProfileDto::setData4(const utility::string_t& value)
{
    m_Data4 = value;
    m_Data4IsSet = true;
}

bool StudentProfileDto::data4IsSet() const
{
    return m_Data4IsSet;
}

void StudentProfileDto::unsetData4()
{
    m_Data4IsSet = false;
}
utility::string_t StudentProfileDto::getData4Label() const
{
    return m_Data4Label;
}

void StudentProfileDto::setData4Label(const utility::string_t& value)
{
    m_Data4Label = value;
    m_Data4LabelIsSet = true;
}

bool StudentProfileDto::data4LabelIsSet() const
{
    return m_Data4LabelIsSet;
}

void StudentProfileDto::unsetData4Label()
{
    m_Data4LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData5() const
{
    return m_Data5;
}

void StudentProfileDto::setData5(const utility::string_t& value)
{
    m_Data5 = value;
    m_Data5IsSet = true;
}

bool StudentProfileDto::data5IsSet() const
{
    return m_Data5IsSet;
}

void StudentProfileDto::unsetData5()
{
    m_Data5IsSet = false;
}
utility::string_t StudentProfileDto::getData5Label() const
{
    return m_Data5Label;
}

void StudentProfileDto::setData5Label(const utility::string_t& value)
{
    m_Data5Label = value;
    m_Data5LabelIsSet = true;
}

bool StudentProfileDto::data5LabelIsSet() const
{
    return m_Data5LabelIsSet;
}

void StudentProfileDto::unsetData5Label()
{
    m_Data5LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData6() const
{
    return m_Data6;
}

void StudentProfileDto::setData6(const utility::string_t& value)
{
    m_Data6 = value;
    m_Data6IsSet = true;
}

bool StudentProfileDto::data6IsSet() const
{
    return m_Data6IsSet;
}

void StudentProfileDto::unsetData6()
{
    m_Data6IsSet = false;
}
utility::string_t StudentProfileDto::getData6Label() const
{
    return m_Data6Label;
}

void StudentProfileDto::setData6Label(const utility::string_t& value)
{
    m_Data6Label = value;
    m_Data6LabelIsSet = true;
}

bool StudentProfileDto::data6LabelIsSet() const
{
    return m_Data6LabelIsSet;
}

void StudentProfileDto::unsetData6Label()
{
    m_Data6LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData7() const
{
    return m_Data7;
}

void StudentProfileDto::setData7(const utility::string_t& value)
{
    m_Data7 = value;
    m_Data7IsSet = true;
}

bool StudentProfileDto::data7IsSet() const
{
    return m_Data7IsSet;
}

void StudentProfileDto::unsetData7()
{
    m_Data7IsSet = false;
}
utility::string_t StudentProfileDto::getData7Label() const
{
    return m_Data7Label;
}

void StudentProfileDto::setData7Label(const utility::string_t& value)
{
    m_Data7Label = value;
    m_Data7LabelIsSet = true;
}

bool StudentProfileDto::data7LabelIsSet() const
{
    return m_Data7LabelIsSet;
}

void StudentProfileDto::unsetData7Label()
{
    m_Data7LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData8() const
{
    return m_Data8;
}

void StudentProfileDto::setData8(const utility::string_t& value)
{
    m_Data8 = value;
    m_Data8IsSet = true;
}

bool StudentProfileDto::data8IsSet() const
{
    return m_Data8IsSet;
}

void StudentProfileDto::unsetData8()
{
    m_Data8IsSet = false;
}
utility::string_t StudentProfileDto::getData8Label() const
{
    return m_Data8Label;
}

void StudentProfileDto::setData8Label(const utility::string_t& value)
{
    m_Data8Label = value;
    m_Data8LabelIsSet = true;
}

bool StudentProfileDto::data8LabelIsSet() const
{
    return m_Data8LabelIsSet;
}

void StudentProfileDto::unsetData8Label()
{
    m_Data8LabelIsSet = false;
}
utility::string_t StudentProfileDto::getData9() const
{
    return m_Data9;
}

void StudentProfileDto::setData9(const utility::string_t& value)
{
    m_Data9 = value;
    m_Data9IsSet = true;
}

bool StudentProfileDto::data9IsSet() const
{
    return m_Data9IsSet;
}

void StudentProfileDto::unsetData9()
{
    m_Data9IsSet = false;
}
utility::string_t StudentProfileDto::getData9Label() const
{
    return m_Data9Label;
}

void StudentProfileDto::setData9Label(const utility::string_t& value)
{
    m_Data9Label = value;
    m_Data9LabelIsSet = true;
}

bool StudentProfileDto::data9LabelIsSet() const
{
    return m_Data9LabelIsSet;
}

void StudentProfileDto::unsetData9Label()
{
    m_Data9LabelIsSet = false;
}
utility::string_t StudentProfileDto::getBusinessID() const
{
    return m_BusinessID;
}

void StudentProfileDto::setBusinessID(const utility::string_t& value)
{
    m_BusinessID = value;
    m_BusinessIDIsSet = true;
}

bool StudentProfileDto::businessIDIsSet() const
{
    return m_BusinessIDIsSet;
}

void StudentProfileDto::unsetBusinessID()
{
    m_BusinessIDIsSet = false;
}
utility::string_t StudentProfileDto::getContactID() const
{
    return m_ContactID;
}

void StudentProfileDto::setContactID(const utility::string_t& value)
{
    m_ContactID = value;
    m_ContactIDIsSet = true;
}

bool StudentProfileDto::contactIDIsSet() const
{
    return m_ContactIDIsSet;
}

void StudentProfileDto::unsetContactID()
{
    m_ContactIDIsSet = false;
}
utility::string_t StudentProfileDto::getBusinessProfileRecordID() const
{
    return m_BusinessProfileRecordID;
}

void StudentProfileDto::setBusinessProfileRecordID(const utility::string_t& value)
{
    m_BusinessProfileRecordID = value;
    m_BusinessProfileRecordIDIsSet = true;
}

bool StudentProfileDto::businessProfileRecordIDIsSet() const
{
    return m_BusinessProfileRecordIDIsSet;
}

void StudentProfileDto::unsetBusinessProfileRecordID()
{
    m_BusinessProfileRecordIDIsSet = false;
}
}
}
}
}


