/**
 * LicensingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/LicenseDtoListEnvelope.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



LicenseDtoListEnvelope::LicenseDtoListEnvelope()
{
    m_IsSuccess = false;
    m_IsSuccessIsSet = false;
    m_ErrorMessage = utility::conversions::to_string_t("");
    m_ErrorMessageIsSet = false;
    m_CorrelationId = utility::conversions::to_string_t("");
    m_CorrelationIdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_HttpStatus = 0;
    m_HttpStatusIsSet = false;
    m_ErrorCode = utility::conversions::to_string_t("");
    m_ErrorCodeIsSet = false;
    m_ValidationDetailsIsSet = false;
    m_ActivityId = utility::conversions::to_string_t("");
    m_ActivityIdIsSet = false;
    m_ResultIsSet = false;
}

LicenseDtoListEnvelope::~LicenseDtoListEnvelope()
{
}

void LicenseDtoListEnvelope::validate()
{
    // TODO: implement validation
}

web::json::value LicenseDtoListEnvelope::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IsSuccessIsSet)
    {
        val[utility::conversions::to_string_t(U("isSuccess"))] = ModelBase::toJson(m_IsSuccess);
    }
    if(m_ErrorMessageIsSet)
    {
        val[utility::conversions::to_string_t(U("errorMessage"))] = ModelBase::toJson(m_ErrorMessage);
    }
    if(m_CorrelationIdIsSet)
    {
        val[utility::conversions::to_string_t(U("correlationId"))] = ModelBase::toJson(m_CorrelationId);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_HttpStatusIsSet)
    {
        val[utility::conversions::to_string_t(U("httpStatus"))] = ModelBase::toJson(m_HttpStatus);
    }
    if(m_ErrorCodeIsSet)
    {
        val[utility::conversions::to_string_t(U("errorCode"))] = ModelBase::toJson(m_ErrorCode);
    }
    if(m_ValidationDetailsIsSet)
    {
        val[utility::conversions::to_string_t(U("validationDetails"))] = ModelBase::toJson(m_ValidationDetails);
    }
    if(m_ActivityIdIsSet)
    {
        val[utility::conversions::to_string_t(U("activityId"))] = ModelBase::toJson(m_ActivityId);
    }
    if(m_ResultIsSet)
    {
        val[utility::conversions::to_string_t(U("result"))] = ModelBase::toJson(m_Result);
    }

    return val;
}

bool LicenseDtoListEnvelope::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("isSuccess"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("isSuccess")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsSuccess);
            setIsSuccess(refVal_setIsSuccess);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("errorMessage"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("errorMessage")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setErrorMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrorMessage);
            setErrorMessage(refVal_setErrorMessage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("correlationId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("correlationId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCorrelationId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCorrelationId);
            setCorrelationId(refVal_setCorrelationId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("httpStatus"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("httpStatus")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setHttpStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHttpStatus);
            setHttpStatus(refVal_setHttpStatus);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("errorCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("errorCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setErrorCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrorCode);
            setErrorCode(refVal_setErrorCode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("validationDetails"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("validationDetails")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::vector<utility::string_t>> refVal_setValidationDetails;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValidationDetails);
            setValidationDetails(refVal_setValidationDetails);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("activityId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("activityId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setActivityId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActivityId);
            setActivityId(refVal_setActivityId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("result"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("result")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<LicenseDto>> refVal_setResult;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResult);
            setResult(refVal_setResult);
        }
    }
    return ok;
}

void LicenseDtoListEnvelope::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IsSuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("isSuccess")), m_IsSuccess));
    }
    if(m_ErrorMessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("errorMessage")), m_ErrorMessage));
    }
    if(m_CorrelationIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("correlationId")), m_CorrelationId));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_HttpStatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("httpStatus")), m_HttpStatus));
    }
    if(m_ErrorCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("errorCode")), m_ErrorCode));
    }
    if(m_ValidationDetailsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("validationDetails")), m_ValidationDetails));
    }
    if(m_ActivityIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("activityId")), m_ActivityId));
    }
    if(m_ResultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("result")), m_Result));
    }
}

bool LicenseDtoListEnvelope::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("isSuccess"))))
    {
        bool refVal_setIsSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("isSuccess"))), refVal_setIsSuccess );
        setIsSuccess(refVal_setIsSuccess);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("errorMessage"))))
    {
        utility::string_t refVal_setErrorMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("errorMessage"))), refVal_setErrorMessage );
        setErrorMessage(refVal_setErrorMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("correlationId"))))
    {
        utility::string_t refVal_setCorrelationId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("correlationId"))), refVal_setCorrelationId );
        setCorrelationId(refVal_setCorrelationId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("httpStatus"))))
    {
        int32_t refVal_setHttpStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("httpStatus"))), refVal_setHttpStatus );
        setHttpStatus(refVal_setHttpStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("errorCode"))))
    {
        utility::string_t refVal_setErrorCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("errorCode"))), refVal_setErrorCode );
        setErrorCode(refVal_setErrorCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("validationDetails"))))
    {
        std::map<utility::string_t, std::vector<utility::string_t>> refVal_setValidationDetails;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("validationDetails"))), refVal_setValidationDetails );
        setValidationDetails(refVal_setValidationDetails);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("activityId"))))
    {
        utility::string_t refVal_setActivityId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("activityId"))), refVal_setActivityId );
        setActivityId(refVal_setActivityId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("result"))))
    {
        std::vector<std::shared_ptr<LicenseDto>> refVal_setResult;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("result"))), refVal_setResult );
        setResult(refVal_setResult);
    }
    return ok;
}

bool LicenseDtoListEnvelope::isIsSuccess() const
{
    return m_IsSuccess;
}

void LicenseDtoListEnvelope::setIsSuccess(bool value)
{
    m_IsSuccess = value;
    m_IsSuccessIsSet = true;
}

bool LicenseDtoListEnvelope::isSuccessIsSet() const
{
    return m_IsSuccessIsSet;
}

void LicenseDtoListEnvelope::unsetIsSuccess()
{
    m_IsSuccessIsSet = false;
}
utility::string_t LicenseDtoListEnvelope::getErrorMessage() const
{
    return m_ErrorMessage;
}

void LicenseDtoListEnvelope::setErrorMessage(const utility::string_t& value)
{
    m_ErrorMessage = value;
    m_ErrorMessageIsSet = true;
}

bool LicenseDtoListEnvelope::errorMessageIsSet() const
{
    return m_ErrorMessageIsSet;
}

void LicenseDtoListEnvelope::unsetErrorMessage()
{
    m_ErrorMessageIsSet = false;
}
utility::string_t LicenseDtoListEnvelope::getCorrelationId() const
{
    return m_CorrelationId;
}

void LicenseDtoListEnvelope::setCorrelationId(const utility::string_t& value)
{
    m_CorrelationId = value;
    m_CorrelationIdIsSet = true;
}

bool LicenseDtoListEnvelope::correlationIdIsSet() const
{
    return m_CorrelationIdIsSet;
}

void LicenseDtoListEnvelope::unsetCorrelationId()
{
    m_CorrelationIdIsSet = false;
}
utility::datetime LicenseDtoListEnvelope::getTimestamp() const
{
    return m_Timestamp;
}

void LicenseDtoListEnvelope::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool LicenseDtoListEnvelope::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void LicenseDtoListEnvelope::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
int32_t LicenseDtoListEnvelope::getHttpStatus() const
{
    return m_HttpStatus;
}

void LicenseDtoListEnvelope::setHttpStatus(int32_t value)
{
    m_HttpStatus = value;
    m_HttpStatusIsSet = true;
}

bool LicenseDtoListEnvelope::httpStatusIsSet() const
{
    return m_HttpStatusIsSet;
}

void LicenseDtoListEnvelope::unsetHttpStatus()
{
    m_HttpStatusIsSet = false;
}
utility::string_t LicenseDtoListEnvelope::getErrorCode() const
{
    return m_ErrorCode;
}

void LicenseDtoListEnvelope::setErrorCode(const utility::string_t& value)
{
    m_ErrorCode = value;
    m_ErrorCodeIsSet = true;
}

bool LicenseDtoListEnvelope::errorCodeIsSet() const
{
    return m_ErrorCodeIsSet;
}

void LicenseDtoListEnvelope::unsetErrorCode()
{
    m_ErrorCodeIsSet = false;
}
std::map<utility::string_t, std::vector<utility::string_t>>& LicenseDtoListEnvelope::getValidationDetails()
{
    return m_ValidationDetails;
}

void LicenseDtoListEnvelope::setValidationDetails(const std::map<utility::string_t, std::vector<utility::string_t>>& value)
{
    m_ValidationDetails = value;
    m_ValidationDetailsIsSet = true;
}

bool LicenseDtoListEnvelope::validationDetailsIsSet() const
{
    return m_ValidationDetailsIsSet;
}

void LicenseDtoListEnvelope::unsetValidationDetails()
{
    m_ValidationDetailsIsSet = false;
}
utility::string_t LicenseDtoListEnvelope::getActivityId() const
{
    return m_ActivityId;
}

void LicenseDtoListEnvelope::setActivityId(const utility::string_t& value)
{
    m_ActivityId = value;
    m_ActivityIdIsSet = true;
}

bool LicenseDtoListEnvelope::activityIdIsSet() const
{
    return m_ActivityIdIsSet;
}

void LicenseDtoListEnvelope::unsetActivityId()
{
    m_ActivityIdIsSet = false;
}
std::vector<std::shared_ptr<LicenseDto>>& LicenseDtoListEnvelope::getResult()
{
    return m_Result;
}

void LicenseDtoListEnvelope::setResult(const std::vector<std::shared_ptr<LicenseDto>>& value)
{
    m_Result = value;
    m_ResultIsSet = true;
}

bool LicenseDtoListEnvelope::resultIsSet() const
{
    return m_ResultIsSet;
}

void LicenseDtoListEnvelope::unsetResult()
{
    m_ResultIsSet = false;
}
}
}
}
}


