/**
 * ServicesService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ServiceLevelAgreementUpdateDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



ServiceLevelAgreementUpdateDto::ServiceLevelAgreementUpdateDto()
{
    m_ServiceId = utility::conversions::to_string_t("");
    m_ServiceIdIsSet = false;
    m_ServiceLevelId = utility::conversions::to_string_t("");
    m_ServiceLevelIdIsSet = false;
    m_ContactId = utility::conversions::to_string_t("");
    m_ContactIdIsSet = false;
}

ServiceLevelAgreementUpdateDto::~ServiceLevelAgreementUpdateDto()
{
}

void ServiceLevelAgreementUpdateDto::validate()
{
    // TODO: implement validation
}

web::json::value ServiceLevelAgreementUpdateDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ServiceIdIsSet)
    {
        val[utility::conversions::to_string_t(U("serviceId"))] = ModelBase::toJson(m_ServiceId);
    }
    if(m_ServiceLevelIdIsSet)
    {
        val[utility::conversions::to_string_t(U("serviceLevelId"))] = ModelBase::toJson(m_ServiceLevelId);
    }
    if(m_ContactIdIsSet)
    {
        val[utility::conversions::to_string_t(U("contactId"))] = ModelBase::toJson(m_ContactId);
    }

    return val;
}

bool ServiceLevelAgreementUpdateDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("serviceId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("serviceId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceId);
            setServiceId(refVal_setServiceId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("serviceLevelId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("serviceLevelId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceLevelId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceLevelId);
            setServiceLevelId(refVal_setServiceLevelId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("contactId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("contactId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContactId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContactId);
            setContactId(refVal_setContactId);
        }
    }
    return ok;
}

void ServiceLevelAgreementUpdateDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ServiceIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("serviceId")), m_ServiceId));
    }
    if(m_ServiceLevelIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("serviceLevelId")), m_ServiceLevelId));
    }
    if(m_ContactIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("contactId")), m_ContactId));
    }
}

bool ServiceLevelAgreementUpdateDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("serviceId"))))
    {
        utility::string_t refVal_setServiceId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("serviceId"))), refVal_setServiceId );
        setServiceId(refVal_setServiceId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("serviceLevelId"))))
    {
        utility::string_t refVal_setServiceLevelId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("serviceLevelId"))), refVal_setServiceLevelId );
        setServiceLevelId(refVal_setServiceLevelId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("contactId"))))
    {
        utility::string_t refVal_setContactId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("contactId"))), refVal_setContactId );
        setContactId(refVal_setContactId);
    }
    return ok;
}

utility::string_t ServiceLevelAgreementUpdateDto::getServiceId() const
{
    return m_ServiceId;
}

void ServiceLevelAgreementUpdateDto::setServiceId(const utility::string_t& value)
{
    m_ServiceId = value;
    m_ServiceIdIsSet = true;
}

bool ServiceLevelAgreementUpdateDto::serviceIdIsSet() const
{
    return m_ServiceIdIsSet;
}

void ServiceLevelAgreementUpdateDto::unsetServiceId()
{
    m_ServiceIdIsSet = false;
}
utility::string_t ServiceLevelAgreementUpdateDto::getServiceLevelId() const
{
    return m_ServiceLevelId;
}

void ServiceLevelAgreementUpdateDto::setServiceLevelId(const utility::string_t& value)
{
    m_ServiceLevelId = value;
    m_ServiceLevelIdIsSet = true;
}

bool ServiceLevelAgreementUpdateDto::serviceLevelIdIsSet() const
{
    return m_ServiceLevelIdIsSet;
}

void ServiceLevelAgreementUpdateDto::unsetServiceLevelId()
{
    m_ServiceLevelIdIsSet = false;
}
utility::string_t ServiceLevelAgreementUpdateDto::getContactId() const
{
    return m_ContactId;
}

void ServiceLevelAgreementUpdateDto::setContactId(const utility::string_t& value)
{
    m_ContactId = value;
    m_ContactIdIsSet = true;
}

bool ServiceLevelAgreementUpdateDto::contactIdIsSet() const
{
    return m_ContactIdIsSet;
}

void ServiceLevelAgreementUpdateDto::unsetContactId()
{
    m_ContactIdIsSet = false;
}
}
}
}
}


