/**
 * HrmsService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RequiredSkillsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_RequiredSkillsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_RequiredSkillsApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/EmptyEnvelope.h"
#include "CppRestOpenAPIClient/model/ErrorEnvelope.h"
#include "CppRestOpenAPIClient/model/Int32Envelope.h"
#include "CppRestOpenAPIClient/model/Operation.h"
#include "CppRestOpenAPIClient/model/RequiredSkillRecordCreateDto.h"
#include "CppRestOpenAPIClient/model/RequiredSkillRecordDtoEnvelope.h"
#include "CppRestOpenAPIClient/model/RequiredSkillRecordDtoListEnvelope.h"
#include "CppRestOpenAPIClient/model/RequiredSkillRecordUpdateDto.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  RequiredSkillsApi 
{
public:

    explicit RequiredSkillsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~RequiredSkillsApi();

    /// <summary>
    /// Create a required skill
    /// </summary>
    /// <remarks>
    /// Creates a new required-skill record for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="requiredSkillRecordCreateDto"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> createRequiredSkillAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<RequiredSkillRecordCreateDto>> requiredSkillRecordCreateDto
    ) const;
    /// <summary>
    /// Delete a required skill
    /// </summary>
    /// <remarks>
    /// Deletes a required-skill record for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="requiredSkillId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> deleteRequiredSkillAsync(
        utility::string_t tenantId,
        utility::string_t requiredSkillId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Get required skill by ID
    /// </summary>
    /// <remarks>
    /// Retrieves a specific required-skill record by its identifier.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="requiredSkillId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<RequiredSkillRecordDtoEnvelope>> getRequiredSkillByIdAsync(
        utility::string_t tenantId,
        utility::string_t requiredSkillId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Get required skills
    /// </summary>
    /// <remarks>
    /// Retrieves required-skill records for the specified tenant. Filter by &#x60;$filter&#x3D;JobOfferId eq &#39;...&#39;&#x60; or &#x60;EmployerProfileId eq &#39;...&#39;&#x60;.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<RequiredSkillRecordDtoListEnvelope>> getRequiredSkillsAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Count required skills
    /// </summary>
    /// <remarks>
    /// Counts required-skill records for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<Int32Envelope>> getRequiredSkillsCountAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Patch a required skill
    /// </summary>
    /// <remarks>
    /// Partially updates an existing required-skill record for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="requiredSkillId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="operation"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> patchRequiredSkillAsync(
        utility::string_t tenantId,
        utility::string_t requiredSkillId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::vector<std::shared_ptr<Operation>>> operation
    ) const;
    /// <summary>
    /// Update a required skill
    /// </summary>
    /// <remarks>
    /// Updates an existing required-skill record for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="requiredSkillId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="requiredSkillRecordUpdateDto"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> updateRequiredSkillAsync(
        utility::string_t tenantId,
        utility::string_t requiredSkillId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<RequiredSkillRecordUpdateDto>> requiredSkillRecordUpdateDto
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_RequiredSkillsApi_H_ */

