/**
 * SupportService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WarrantyRequestsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_WarrantyRequestsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_WarrantyRequestsApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/EmptyEnvelope.h"
#include "CppRestOpenAPIClient/model/Int32Envelope.h"
#include "CppRestOpenAPIClient/model/WarrantyRequestCreateDto.h"
#include "CppRestOpenAPIClient/model/WarrantyRequestDtoEnvelope.h"
#include "CppRestOpenAPIClient/model/WarrantyRequestDtoListEnvelope.h"
#include "CppRestOpenAPIClient/model/WarrantyRequestUpdateDto.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  WarrantyRequestsApi 
{
public:

    explicit WarrantyRequestsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~WarrantyRequestsApi();

    /// <summary>
    /// Create a warranty request
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="warrantyRequestCreateDto"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> createWarrantyRequestAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<WarrantyRequestCreateDto>> warrantyRequestCreateDto
    ) const;
    /// <summary>
    /// Delete a warranty request
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="warrantyRequestId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> deleteWarrantyRequestAsync(
        utility::string_t tenantId,
        utility::string_t warrantyRequestId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Retrieve a warranty request by ID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="warrantyRequestId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<WarrantyRequestDtoEnvelope>> getWarrantyRequestAsync(
        utility::string_t tenantId,
        utility::string_t warrantyRequestId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Retrieve warranty requests
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<WarrantyRequestDtoListEnvelope>> getWarrantyRequestsAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Get warranty requests count
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<Int32Envelope>> getWarrantyRequestsCountAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Update a warranty request
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="warrantyRequestId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="warrantyRequestUpdateDto"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> updateWarrantyRequestAsync(
        utility::string_t tenantId,
        utility::string_t warrantyRequestId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<WarrantyRequestUpdateDto>> warrantyRequestUpdateDto
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_WarrantyRequestsApi_H_ */

