/**
 * SystemService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Module.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Module::Module()
{
    m_Enable = false;
    m_EnableIsSet = false;
    m_Active = false;
    m_ActiveIsSet = false;
    m_Order = 0;
    m_OrderIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_FullName = utility::conversions::to_string_t("");
    m_FullNameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Configuration = utility::conversions::to_string_t("");
    m_ConfigurationIsSet = false;
    m_Author = utility::conversions::to_string_t("");
    m_AuthorIsSet = false;
    m_AuthorUrl = utility::conversions::to_string_t("");
    m_AuthorUrlIsSet = false;
    m_License = utility::conversions::to_string_t("");
    m_LicenseIsSet = false;
    m_RequireLicenseAcceptance = false;
    m_RequireLicenseAcceptanceIsSet = false;
    m_Repository = utility::conversions::to_string_t("");
    m_RepositoryIsSet = false;
    m_Path = utility::conversions::to_string_t("");
    m_PathIsSet = false;
    m_Icon = utility::conversions::to_string_t("");
    m_IconIsSet = false;
    m_Image = utility::conversions::to_string_t("");
    m_ImageIsSet = false;
    m_NuSpecPath = utility::conversions::to_string_t("");
    m_NuSpecPathIsSet = false;
    m_Manifest = utility::conversions::to_string_t("");
    m_ManifestIsSet = false;
    m_Documentation = utility::conversions::to_string_t("");
    m_DocumentationIsSet = false;
    m_Website = utility::conversions::to_string_t("");
    m_WebsiteIsSet = false;
    m_Logo = utility::conversions::to_string_t("");
    m_LogoIsSet = false;
    m_SwaggerSpecIsSet = false;
    m_SwaggerSpecsIsSet = false;
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_AssemblyPathsIsSet = false;
    m_MarkedForDeletion = false;
    m_MarkedForDeletionIsSet = false;
    m_Version = utility::conversions::to_string_t("");
    m_VersionIsSet = false;
}

Module::~Module()
{
}

void Module::validate()
{
    // TODO: implement validation
}

web::json::value Module::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EnableIsSet)
    {
        val[utility::conversions::to_string_t(U("enable"))] = ModelBase::toJson(m_Enable);
    }
    if(m_ActiveIsSet)
    {
        val[utility::conversions::to_string_t(U("active"))] = ModelBase::toJson(m_Active);
    }
    if(m_OrderIsSet)
    {
        val[utility::conversions::to_string_t(U("order"))] = ModelBase::toJson(m_Order);
    }
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_FullNameIsSet)
    {
        val[utility::conversions::to_string_t(U("fullName"))] = ModelBase::toJson(m_FullName);
    }
    if(m_DescriptionIsSet)
    {
        val[utility::conversions::to_string_t(U("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t(U("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_ConfigurationIsSet)
    {
        val[utility::conversions::to_string_t(U("configuration"))] = ModelBase::toJson(m_Configuration);
    }
    if(m_AuthorIsSet)
    {
        val[utility::conversions::to_string_t(U("author"))] = ModelBase::toJson(m_Author);
    }
    if(m_AuthorUrlIsSet)
    {
        val[utility::conversions::to_string_t(U("authorUrl"))] = ModelBase::toJson(m_AuthorUrl);
    }
    if(m_LicenseIsSet)
    {
        val[utility::conversions::to_string_t(U("license"))] = ModelBase::toJson(m_License);
    }
    if(m_RequireLicenseAcceptanceIsSet)
    {
        val[utility::conversions::to_string_t(U("requireLicenseAcceptance"))] = ModelBase::toJson(m_RequireLicenseAcceptance);
    }
    if(m_RepositoryIsSet)
    {
        val[utility::conversions::to_string_t(U("repository"))] = ModelBase::toJson(m_Repository);
    }
    if(m_PathIsSet)
    {
        val[utility::conversions::to_string_t(U("path"))] = ModelBase::toJson(m_Path);
    }
    if(m_IconIsSet)
    {
        val[utility::conversions::to_string_t(U("icon"))] = ModelBase::toJson(m_Icon);
    }
    if(m_ImageIsSet)
    {
        val[utility::conversions::to_string_t(U("image"))] = ModelBase::toJson(m_Image);
    }
    if(m_NuSpecPathIsSet)
    {
        val[utility::conversions::to_string_t(U("nuSpecPath"))] = ModelBase::toJson(m_NuSpecPath);
    }
    if(m_ManifestIsSet)
    {
        val[utility::conversions::to_string_t(U("manifest"))] = ModelBase::toJson(m_Manifest);
    }
    if(m_DocumentationIsSet)
    {
        val[utility::conversions::to_string_t(U("documentation"))] = ModelBase::toJson(m_Documentation);
    }
    if(m_WebsiteIsSet)
    {
        val[utility::conversions::to_string_t(U("website"))] = ModelBase::toJson(m_Website);
    }
    if(m_LogoIsSet)
    {
        val[utility::conversions::to_string_t(U("logo"))] = ModelBase::toJson(m_Logo);
    }
    if(m_SwaggerSpecIsSet)
    {
        val[utility::conversions::to_string_t(U("swaggerSpec"))] = ModelBase::toJson(m_SwaggerSpec);
    }
    if(m_SwaggerSpecsIsSet)
    {
        val[utility::conversions::to_string_t(U("swaggerSpecs"))] = ModelBase::toJson(m_SwaggerSpecs);
    }
    if(m_UrlIsSet)
    {
        val[utility::conversions::to_string_t(U("url"))] = ModelBase::toJson(m_Url);
    }
    if(m_AssemblyPathsIsSet)
    {
        val[utility::conversions::to_string_t(U("assemblyPaths"))] = ModelBase::toJson(m_AssemblyPaths);
    }
    if(m_MarkedForDeletionIsSet)
    {
        val[utility::conversions::to_string_t(U("markedForDeletion"))] = ModelBase::toJson(m_MarkedForDeletion);
    }
    if(m_VersionIsSet)
    {
        val[utility::conversions::to_string_t(U("version"))] = ModelBase::toJson(m_Version);
    }

    return val;
}

bool Module::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("enable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("enable")));
        if(!fieldValue.is_null())
        {
            bool refVal_setEnable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnable);
            setEnable(refVal_setEnable);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("active"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("active")));
        if(!fieldValue.is_null())
        {
            bool refVal_setActive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActive);
            setActive(refVal_setActive);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("order"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("order")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOrder;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrder);
            setOrder(refVal_setOrder);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("fullName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fullName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFullName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFullName);
            setFullName(refVal_setFullName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("configuration"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("configuration")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setConfiguration;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConfiguration);
            setConfiguration(refVal_setConfiguration);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("author"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("author")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAuthor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthor);
            setAuthor(refVal_setAuthor);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("authorUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("authorUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAuthorUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthorUrl);
            setAuthorUrl(refVal_setAuthorUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("license"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("license")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLicense;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLicense);
            setLicense(refVal_setLicense);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("requireLicenseAcceptance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("requireLicenseAcceptance")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRequireLicenseAcceptance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequireLicenseAcceptance);
            setRequireLicenseAcceptance(refVal_setRequireLicenseAcceptance);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("repository"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("repository")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRepository;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRepository);
            setRepository(refVal_setRepository);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPath);
            setPath(refVal_setPath);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("icon"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("icon")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIcon;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIcon);
            setIcon(refVal_setIcon);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("image"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("image")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setImage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImage);
            setImage(refVal_setImage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("nuSpecPath"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("nuSpecPath")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNuSpecPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNuSpecPath);
            setNuSpecPath(refVal_setNuSpecPath);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("manifest"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("manifest")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManifest;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManifest);
            setManifest(refVal_setManifest);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("documentation"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("documentation")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDocumentation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDocumentation);
            setDocumentation(refVal_setDocumentation);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("website"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("website")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWebsite;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebsite);
            setWebsite(refVal_setWebsite);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("logo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("logo")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogo);
            setLogo(refVal_setLogo);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("swaggerSpec"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("swaggerSpec")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ISwaggerSpec> refVal_setSwaggerSpec;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSwaggerSpec);
            setSwaggerSpec(refVal_setSwaggerSpec);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("swaggerSpecs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("swaggerSpecs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ISwaggerSpec>> refVal_setSwaggerSpecs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSwaggerSpecs);
            setSwaggerSpecs(refVal_setSwaggerSpecs);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("assemblyPaths"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("assemblyPaths")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setAssemblyPaths;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAssemblyPaths);
            setAssemblyPaths(refVal_setAssemblyPaths);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("markedForDeletion"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("markedForDeletion")));
        if(!fieldValue.is_null())
        {
            bool refVal_setMarkedForDeletion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMarkedForDeletion);
            setMarkedForDeletion(refVal_setMarkedForDeletion);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("version")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersion);
            setVersion(refVal_setVersion);
        }
    }
    return ok;
}

void Module::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_EnableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("enable")), m_Enable));
    }
    if(m_ActiveIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("active")), m_Active));
    }
    if(m_OrderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("order")), m_Order));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_FullNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fullName")), m_FullName));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("description")), m_Description));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("type")), m_Type));
    }
    if(m_ConfigurationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("configuration")), m_Configuration));
    }
    if(m_AuthorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("author")), m_Author));
    }
    if(m_AuthorUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("authorUrl")), m_AuthorUrl));
    }
    if(m_LicenseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("license")), m_License));
    }
    if(m_RequireLicenseAcceptanceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("requireLicenseAcceptance")), m_RequireLicenseAcceptance));
    }
    if(m_RepositoryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("repository")), m_Repository));
    }
    if(m_PathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("path")), m_Path));
    }
    if(m_IconIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("icon")), m_Icon));
    }
    if(m_ImageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("image")), m_Image));
    }
    if(m_NuSpecPathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("nuSpecPath")), m_NuSpecPath));
    }
    if(m_ManifestIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("manifest")), m_Manifest));
    }
    if(m_DocumentationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("documentation")), m_Documentation));
    }
    if(m_WebsiteIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("website")), m_Website));
    }
    if(m_LogoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("logo")), m_Logo));
    }
    if(m_SwaggerSpecIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("swaggerSpec")), m_SwaggerSpec));
    }
    if(m_SwaggerSpecsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("swaggerSpecs")), m_SwaggerSpecs));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("url")), m_Url));
    }
    if(m_AssemblyPathsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("assemblyPaths")), m_AssemblyPaths));
    }
    if(m_MarkedForDeletionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("markedForDeletion")), m_MarkedForDeletion));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("version")), m_Version));
    }
}

bool Module::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("enable"))))
    {
        bool refVal_setEnable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("enable"))), refVal_setEnable );
        setEnable(refVal_setEnable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("active"))))
    {
        bool refVal_setActive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("active"))), refVal_setActive );
        setActive(refVal_setActive);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("order"))))
    {
        int32_t refVal_setOrder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("order"))), refVal_setOrder );
        setOrder(refVal_setOrder);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("fullName"))))
    {
        utility::string_t refVal_setFullName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fullName"))), refVal_setFullName );
        setFullName(refVal_setFullName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("configuration"))))
    {
        utility::string_t refVal_setConfiguration;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("configuration"))), refVal_setConfiguration );
        setConfiguration(refVal_setConfiguration);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("author"))))
    {
        utility::string_t refVal_setAuthor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("author"))), refVal_setAuthor );
        setAuthor(refVal_setAuthor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("authorUrl"))))
    {
        utility::string_t refVal_setAuthorUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("authorUrl"))), refVal_setAuthorUrl );
        setAuthorUrl(refVal_setAuthorUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("license"))))
    {
        utility::string_t refVal_setLicense;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("license"))), refVal_setLicense );
        setLicense(refVal_setLicense);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("requireLicenseAcceptance"))))
    {
        bool refVal_setRequireLicenseAcceptance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("requireLicenseAcceptance"))), refVal_setRequireLicenseAcceptance );
        setRequireLicenseAcceptance(refVal_setRequireLicenseAcceptance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("repository"))))
    {
        utility::string_t refVal_setRepository;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("repository"))), refVal_setRepository );
        setRepository(refVal_setRepository);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("path"))))
    {
        utility::string_t refVal_setPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("path"))), refVal_setPath );
        setPath(refVal_setPath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("icon"))))
    {
        utility::string_t refVal_setIcon;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("icon"))), refVal_setIcon );
        setIcon(refVal_setIcon);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("image"))))
    {
        utility::string_t refVal_setImage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("image"))), refVal_setImage );
        setImage(refVal_setImage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("nuSpecPath"))))
    {
        utility::string_t refVal_setNuSpecPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("nuSpecPath"))), refVal_setNuSpecPath );
        setNuSpecPath(refVal_setNuSpecPath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("manifest"))))
    {
        utility::string_t refVal_setManifest;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("manifest"))), refVal_setManifest );
        setManifest(refVal_setManifest);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("documentation"))))
    {
        utility::string_t refVal_setDocumentation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("documentation"))), refVal_setDocumentation );
        setDocumentation(refVal_setDocumentation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("website"))))
    {
        utility::string_t refVal_setWebsite;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("website"))), refVal_setWebsite );
        setWebsite(refVal_setWebsite);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("logo"))))
    {
        utility::string_t refVal_setLogo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("logo"))), refVal_setLogo );
        setLogo(refVal_setLogo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("swaggerSpec"))))
    {
        std::shared_ptr<ISwaggerSpec> refVal_setSwaggerSpec;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("swaggerSpec"))), refVal_setSwaggerSpec );
        setSwaggerSpec(refVal_setSwaggerSpec);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("swaggerSpecs"))))
    {
        std::vector<std::shared_ptr<ISwaggerSpec>> refVal_setSwaggerSpecs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("swaggerSpecs"))), refVal_setSwaggerSpecs );
        setSwaggerSpecs(refVal_setSwaggerSpecs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("assemblyPaths"))))
    {
        std::vector<utility::string_t> refVal_setAssemblyPaths;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("assemblyPaths"))), refVal_setAssemblyPaths );
        setAssemblyPaths(refVal_setAssemblyPaths);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("markedForDeletion"))))
    {
        bool refVal_setMarkedForDeletion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("markedForDeletion"))), refVal_setMarkedForDeletion );
        setMarkedForDeletion(refVal_setMarkedForDeletion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("version"))))
    {
        utility::string_t refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("version"))), refVal_setVersion );
        setVersion(refVal_setVersion);
    }
    return ok;
}

bool Module::isEnable() const
{
    return m_Enable;
}

void Module::setEnable(bool value)
{
    m_Enable = value;
    m_EnableIsSet = true;
}

bool Module::enableIsSet() const
{
    return m_EnableIsSet;
}

void Module::unsetEnable()
{
    m_EnableIsSet = false;
}
bool Module::isActive() const
{
    return m_Active;
}

void Module::setActive(bool value)
{
    m_Active = value;
    m_ActiveIsSet = true;
}

bool Module::activeIsSet() const
{
    return m_ActiveIsSet;
}

void Module::unsetActive()
{
    m_ActiveIsSet = false;
}
int32_t Module::getOrder() const
{
    return m_Order;
}

void Module::setOrder(int32_t value)
{
    m_Order = value;
    m_OrderIsSet = true;
}

bool Module::orderIsSet() const
{
    return m_OrderIsSet;
}

void Module::unsetOrder()
{
    m_OrderIsSet = false;
}
utility::string_t Module::getId() const
{
    return m_Id;
}

void Module::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Module::idIsSet() const
{
    return m_IdIsSet;
}

void Module::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Module::getName() const
{
    return m_Name;
}

void Module::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Module::nameIsSet() const
{
    return m_NameIsSet;
}

void Module::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Module::getFullName() const
{
    return m_FullName;
}

void Module::setFullName(const utility::string_t& value)
{
    m_FullName = value;
    m_FullNameIsSet = true;
}

bool Module::fullNameIsSet() const
{
    return m_FullNameIsSet;
}

void Module::unsetFullName()
{
    m_FullNameIsSet = false;
}
utility::string_t Module::getDescription() const
{
    return m_Description;
}

void Module::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool Module::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void Module::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t Module::getType() const
{
    return m_Type;
}

void Module::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool Module::typeIsSet() const
{
    return m_TypeIsSet;
}

void Module::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t Module::getConfiguration() const
{
    return m_Configuration;
}

void Module::setConfiguration(const utility::string_t& value)
{
    m_Configuration = value;
    m_ConfigurationIsSet = true;
}

bool Module::configurationIsSet() const
{
    return m_ConfigurationIsSet;
}

void Module::unsetConfiguration()
{
    m_ConfigurationIsSet = false;
}
utility::string_t Module::getAuthor() const
{
    return m_Author;
}

void Module::setAuthor(const utility::string_t& value)
{
    m_Author = value;
    m_AuthorIsSet = true;
}

bool Module::authorIsSet() const
{
    return m_AuthorIsSet;
}

void Module::unsetAuthor()
{
    m_AuthorIsSet = false;
}
utility::string_t Module::getAuthorUrl() const
{
    return m_AuthorUrl;
}

void Module::setAuthorUrl(const utility::string_t& value)
{
    m_AuthorUrl = value;
    m_AuthorUrlIsSet = true;
}

bool Module::authorUrlIsSet() const
{
    return m_AuthorUrlIsSet;
}

void Module::unsetAuthorUrl()
{
    m_AuthorUrlIsSet = false;
}
utility::string_t Module::getLicense() const
{
    return m_License;
}

void Module::setLicense(const utility::string_t& value)
{
    m_License = value;
    m_LicenseIsSet = true;
}

bool Module::licenseIsSet() const
{
    return m_LicenseIsSet;
}

void Module::unsetLicense()
{
    m_LicenseIsSet = false;
}
bool Module::isRequireLicenseAcceptance() const
{
    return m_RequireLicenseAcceptance;
}

void Module::setRequireLicenseAcceptance(bool value)
{
    m_RequireLicenseAcceptance = value;
    m_RequireLicenseAcceptanceIsSet = true;
}

bool Module::requireLicenseAcceptanceIsSet() const
{
    return m_RequireLicenseAcceptanceIsSet;
}

void Module::unsetRequireLicenseAcceptance()
{
    m_RequireLicenseAcceptanceIsSet = false;
}
utility::string_t Module::getRepository() const
{
    return m_Repository;
}

void Module::setRepository(const utility::string_t& value)
{
    m_Repository = value;
    m_RepositoryIsSet = true;
}

bool Module::repositoryIsSet() const
{
    return m_RepositoryIsSet;
}

void Module::unsetRepository()
{
    m_RepositoryIsSet = false;
}
utility::string_t Module::getPath() const
{
    return m_Path;
}

void Module::setPath(const utility::string_t& value)
{
    m_Path = value;
    m_PathIsSet = true;
}

bool Module::pathIsSet() const
{
    return m_PathIsSet;
}

void Module::unsetPath()
{
    m_PathIsSet = false;
}
utility::string_t Module::getIcon() const
{
    return m_Icon;
}

void Module::setIcon(const utility::string_t& value)
{
    m_Icon = value;
    m_IconIsSet = true;
}

bool Module::iconIsSet() const
{
    return m_IconIsSet;
}

void Module::unsetIcon()
{
    m_IconIsSet = false;
}
utility::string_t Module::getImage() const
{
    return m_Image;
}

void Module::setImage(const utility::string_t& value)
{
    m_Image = value;
    m_ImageIsSet = true;
}

bool Module::imageIsSet() const
{
    return m_ImageIsSet;
}

void Module::unsetImage()
{
    m_ImageIsSet = false;
}
utility::string_t Module::getNuSpecPath() const
{
    return m_NuSpecPath;
}

void Module::setNuSpecPath(const utility::string_t& value)
{
    m_NuSpecPath = value;
    m_NuSpecPathIsSet = true;
}

bool Module::nuSpecPathIsSet() const
{
    return m_NuSpecPathIsSet;
}

void Module::unsetNuSpecPath()
{
    m_NuSpecPathIsSet = false;
}
utility::string_t Module::getManifest() const
{
    return m_Manifest;
}

void Module::setManifest(const utility::string_t& value)
{
    m_Manifest = value;
    m_ManifestIsSet = true;
}

bool Module::manifestIsSet() const
{
    return m_ManifestIsSet;
}

void Module::unsetManifest()
{
    m_ManifestIsSet = false;
}
utility::string_t Module::getDocumentation() const
{
    return m_Documentation;
}

void Module::setDocumentation(const utility::string_t& value)
{
    m_Documentation = value;
    m_DocumentationIsSet = true;
}

bool Module::documentationIsSet() const
{
    return m_DocumentationIsSet;
}

void Module::unsetDocumentation()
{
    m_DocumentationIsSet = false;
}
utility::string_t Module::getWebsite() const
{
    return m_Website;
}

void Module::setWebsite(const utility::string_t& value)
{
    m_Website = value;
    m_WebsiteIsSet = true;
}

bool Module::websiteIsSet() const
{
    return m_WebsiteIsSet;
}

void Module::unsetWebsite()
{
    m_WebsiteIsSet = false;
}
utility::string_t Module::getLogo() const
{
    return m_Logo;
}

void Module::setLogo(const utility::string_t& value)
{
    m_Logo = value;
    m_LogoIsSet = true;
}

bool Module::logoIsSet() const
{
    return m_LogoIsSet;
}

void Module::unsetLogo()
{
    m_LogoIsSet = false;
}
std::shared_ptr<ISwaggerSpec> Module::getSwaggerSpec() const
{
    return m_SwaggerSpec;
}

void Module::setSwaggerSpec(const std::shared_ptr<ISwaggerSpec>& value)
{
    m_SwaggerSpec = value;
    m_SwaggerSpecIsSet = true;
}

bool Module::swaggerSpecIsSet() const
{
    return m_SwaggerSpecIsSet;
}

void Module::unsetSwaggerSpec()
{
    m_SwaggerSpecIsSet = false;
}
std::vector<std::shared_ptr<ISwaggerSpec>>& Module::getSwaggerSpecs()
{
    return m_SwaggerSpecs;
}

void Module::setSwaggerSpecs(const std::vector<std::shared_ptr<ISwaggerSpec>>& value)
{
    m_SwaggerSpecs = value;
    m_SwaggerSpecsIsSet = true;
}

bool Module::swaggerSpecsIsSet() const
{
    return m_SwaggerSpecsIsSet;
}

void Module::unsetSwaggerSpecs()
{
    m_SwaggerSpecsIsSet = false;
}
utility::string_t Module::getUrl() const
{
    return m_Url;
}

void Module::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool Module::urlIsSet() const
{
    return m_UrlIsSet;
}

void Module::unsetUrl()
{
    m_UrlIsSet = false;
}
std::vector<utility::string_t>& Module::getAssemblyPaths()
{
    return m_AssemblyPaths;
}

void Module::setAssemblyPaths(const std::vector<utility::string_t>& value)
{
    m_AssemblyPaths = value;
    m_AssemblyPathsIsSet = true;
}

bool Module::assemblyPathsIsSet() const
{
    return m_AssemblyPathsIsSet;
}

void Module::unsetAssemblyPaths()
{
    m_AssemblyPathsIsSet = false;
}
bool Module::isMarkedForDeletion() const
{
    return m_MarkedForDeletion;
}

void Module::setMarkedForDeletion(bool value)
{
    m_MarkedForDeletion = value;
    m_MarkedForDeletionIsSet = true;
}

bool Module::markedForDeletionIsSet() const
{
    return m_MarkedForDeletionIsSet;
}

void Module::unsetMarkedForDeletion()
{
    m_MarkedForDeletionIsSet = false;
}
utility::string_t Module::getVersion() const
{
    return m_Version;
}

void Module::setVersion(const utility::string_t& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool Module::versionIsSet() const
{
    return m_VersionIsSet;
}

void Module::unsetVersion()
{
    m_VersionIsSet = false;
}
}
}
}
}


