/**
 * ContentService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MeasurementOptions.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementOptions_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementOptions_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  MeasurementOptions
    : public ModelBase
{
public:
    MeasurementOptions();
    virtual ~MeasurementOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MeasurementOptions members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDefaultWeightUnit() const;
    bool defaultWeightUnitIsSet() const;
    void unsetDefaultWeightUnit();

    void setDefaultWeightUnit(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDefaultDimensionUInit() const;
    bool defaultDimensionUInitIsSet() const;
    void unsetDefaultDimensionUInit();

    void setDefaultDimensionUInit(const utility::string_t& value);


protected:
    utility::string_t m_DefaultWeightUnit;
    bool m_DefaultWeightUnitIsSet;
    utility::string_t m_DefaultDimensionUInit;
    bool m_DefaultDimensionUInitIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementOptions_H_ */
