/**
 * ContentService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WebPortalUpdateDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_WebPortalUpdateDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_WebPortalUpdateDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  WebPortalUpdateDto
    : public ModelBase
{
public:
    WebPortalUpdateDto();
    virtual ~WebPortalUpdateDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// WebPortalUpdateDto members

    /// <summary>
    /// 
    /// </summary>
    bool isRoot() const;
    bool rootIsSet() const;
    void unsetRoot();

    void setRoot(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();

    void setTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDomain() const;
    bool domainIsSet() const;
    void unsetDomain();

    void setDomain(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isDisabled() const;
    bool disabledIsSet() const;
    void unsetDisabled();

    void setDisabled(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();

    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getWebsiteThemeId() const;
    bool websiteThemeIdIsSet() const;
    void unsetWebsiteThemeId();

    void setWebsiteThemeId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBusinessDomainId() const;
    bool businessDomainIdIsSet() const;
    void unsetBusinessDomainId();

    void setBusinessDomainId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBusinessPortalApplicationId() const;
    bool businessPortalApplicationIdIsSet() const;
    void unsetBusinessPortalApplicationId();

    void setBusinessPortalApplicationId(const utility::string_t& value);


protected:
    bool m_Root;
    bool m_RootIsSet;
    utility::string_t m_Title;
    bool m_TitleIsSet;
    utility::string_t m_Domain;
    bool m_DomainIsSet;
    bool m_Disabled;
    bool m_DisabledIsSet;
    utility::string_t m_Description;
    bool m_DescriptionIsSet;
    utility::string_t m_WebsiteThemeId;
    bool m_WebsiteThemeIdIsSet;
    utility::string_t m_BusinessDomainId;
    bool m_BusinessDomainIdIsSet;
    utility::string_t m_BusinessPortalApplicationId;
    bool m_BusinessPortalApplicationIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_WebPortalUpdateDto_H_ */
