/**
 * ManufacturingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProductionPlansApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ProductionPlansApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ProductionPlansApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/EmptyEnvelope.h"
#include "CppRestOpenAPIClient/model/ErrorEnvelope.h"
#include "CppRestOpenAPIClient/model/Int32Envelope.h"
#include "CppRestOpenAPIClient/model/PatchOperation.h"
#include "CppRestOpenAPIClient/model/ProductionPlanCreateDto.h"
#include "CppRestOpenAPIClient/model/ProductionPlanDto.h"
#include "CppRestOpenAPIClient/model/ProductionPlanDtoCollectionQueryParameters.h"
#include "CppRestOpenAPIClient/model/ProductionPlanDtoListEnvelope.h"
#include "CppRestOpenAPIClient/model/ProductionPlanUpdateDto.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ProductionPlansApi 
{
public:

    explicit ProductionPlansApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ProductionPlansApi();

    /// <summary>
    /// Create a new production plan
    /// </summary>
    /// <remarks>
    /// Creates a new production plan for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="productionPlanCreateDto"> (optional)</param>
    pplx::task<void> createProductionPlanAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<ProductionPlanCreateDto>> productionPlanCreateDto
    ) const;
    /// <summary>
    /// Delete a production plan
    /// </summary>
    /// <remarks>
    /// Deletes a production plan for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="id"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<void> deleteProductionPlanAsync(
        utility::string_t tenantId,
        utility::string_t id,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Get production plan by ID
    /// </summary>
    /// <remarks>
    /// Retrieves a specific production plan by its identifier.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="id"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<ProductionPlanDto>> getProductionPlanByIdAsync(
        utility::string_t tenantId,
        utility::string_t id,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion
    ) const;
    /// <summary>
    /// Get all production plans
    /// </summary>
    /// <remarks>
    /// Retrieves all production plans for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="productionPlanDtoCollectionQueryParameters"> (optional)</param>
    pplx::task<std::shared_ptr<ProductionPlanDtoListEnvelope>> getProductionPlansAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<ProductionPlanDtoCollectionQueryParameters>> productionPlanDtoCollectionQueryParameters
    ) const;
    /// <summary>
    /// Get production plans count
    /// </summary>
    /// <remarks>
    /// Returns the count of production plans for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="productionPlanDtoCollectionQueryParameters"> (optional)</param>
    pplx::task<std::shared_ptr<Int32Envelope>> getProductionPlansCountAsync(
        utility::string_t tenantId,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<ProductionPlanDtoCollectionQueryParameters>> productionPlanDtoCollectionQueryParameters
    ) const;
    /// <summary>
    /// Patch a production plan
    /// </summary>
    /// <remarks>
    /// Patch a production plan
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="id"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="patchOperation"> (optional)</param>
    pplx::task<std::shared_ptr<EmptyEnvelope>> patchProductionPlanAsync(
        utility::string_t tenantId,
        utility::string_t id,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::vector<std::shared_ptr<PatchOperation>>> patchOperation
    ) const;
    /// <summary>
    /// Update a production plan
    /// </summary>
    /// <remarks>
    /// Updates an existing production plan for the specified tenant.
    /// </remarks>
    /// <param name="tenantId"></param>
    /// <param name="id"></param>
    /// <param name="apiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xApiVersion"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="productionPlanUpdateDto"> (optional)</param>
    pplx::task<void> updateProductionPlanAsync(
        utility::string_t tenantId,
        utility::string_t id,
        boost::optional<utility::string_t> apiVersion,
        boost::optional<utility::string_t> xApiVersion,
        boost::optional<std::shared_ptr<ProductionPlanUpdateDto>> productionPlanUpdateDto
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ProductionPlansApi_H_ */

