/**
 * UsersService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateAvatarAsync_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAvatarAsync_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAvatarAsync_request_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/HttpContent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  UpdateAvatarAsync_request
    : public ModelBase
{
public:
    UpdateAvatarAsync_request();
    virtual ~UpdateAvatarAsync_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UpdateAvatarAsync_request members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<HttpContent> getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();

    void setAvatar(const std::shared_ptr<HttpContent>& value);


protected:
    std::shared_ptr<HttpContent> m_Avatar;
    bool m_AvatarIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateAvatarAsync_request_H_ */
