/**
 * SocialService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SocialPostAttachmentUpdateDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



SocialPostAttachmentUpdateDto::SocialPostAttachmentUpdateDto()
{
    m_Notes = utility::conversions::to_string_t("");
    m_NotesIsSet = false;
    m_Metadata = utility::conversions::to_string_t("");
    m_MetadataIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Author = utility::conversions::to_string_t("");
    m_AuthorIsSet = false;
    m_IsFolder = false;
    m_IsFolderIsSet = false;
    m_FileName = utility::conversions::to_string_t("");
    m_FileNameIsSet = false;
    m_Abstract = utility::conversions::to_string_t("");
    m_AbstractIsSet = false;
    m_KeyWords = utility::conversions::to_string_t("");
    m_KeyWordsIsSet = false;
    m_ValidResponse = false;
    m_ValidResponseIsSet = false;
    m_ParentFileUploadID = utility::conversions::to_string_t("");
    m_ParentFileUploadIDIsSet = false;
    m_FilePath = utility::conversions::to_string_t("");
    m_FilePathIsSet = false;
}

SocialPostAttachmentUpdateDto::~SocialPostAttachmentUpdateDto()
{
}

void SocialPostAttachmentUpdateDto::validate()
{
    // TODO: implement validation
}

web::json::value SocialPostAttachmentUpdateDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NotesIsSet)
    {
        val[utility::conversions::to_string_t(U("notes"))] = ModelBase::toJson(m_Notes);
    }
    if(m_MetadataIsSet)
    {
        val[utility::conversions::to_string_t(U("metadata"))] = ModelBase::toJson(m_Metadata);
    }
    if(m_TitleIsSet)
    {
        val[utility::conversions::to_string_t(U("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_AuthorIsSet)
    {
        val[utility::conversions::to_string_t(U("author"))] = ModelBase::toJson(m_Author);
    }
    if(m_IsFolderIsSet)
    {
        val[utility::conversions::to_string_t(U("isFolder"))] = ModelBase::toJson(m_IsFolder);
    }
    if(m_FileNameIsSet)
    {
        val[utility::conversions::to_string_t(U("fileName"))] = ModelBase::toJson(m_FileName);
    }
    if(m_AbstractIsSet)
    {
        val[utility::conversions::to_string_t(U("abstract"))] = ModelBase::toJson(m_Abstract);
    }
    if(m_KeyWordsIsSet)
    {
        val[utility::conversions::to_string_t(U("keyWords"))] = ModelBase::toJson(m_KeyWords);
    }
    if(m_ValidResponseIsSet)
    {
        val[utility::conversions::to_string_t(U("validResponse"))] = ModelBase::toJson(m_ValidResponse);
    }
    if(m_ParentFileUploadIDIsSet)
    {
        val[utility::conversions::to_string_t(U("parentFileUploadID"))] = ModelBase::toJson(m_ParentFileUploadID);
    }
    if(m_FilePathIsSet)
    {
        val[utility::conversions::to_string_t(U("filePath"))] = ModelBase::toJson(m_FilePath);
    }

    return val;
}

bool SocialPostAttachmentUpdateDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("notes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("notes")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNotes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotes);
            setNotes(refVal_setNotes);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("metadata")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("author"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("author")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAuthor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthor);
            setAuthor(refVal_setAuthor);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("isFolder"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("isFolder")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsFolder;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsFolder);
            setIsFolder(refVal_setIsFolder);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("fileName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fileName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFileName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFileName);
            setFileName(refVal_setFileName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("abstract"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("abstract")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAbstract;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAbstract);
            setAbstract(refVal_setAbstract);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("keyWords"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("keyWords")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKeyWords;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKeyWords);
            setKeyWords(refVal_setKeyWords);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("validResponse"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("validResponse")));
        if(!fieldValue.is_null())
        {
            bool refVal_setValidResponse;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValidResponse);
            setValidResponse(refVal_setValidResponse);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("parentFileUploadID"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("parentFileUploadID")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setParentFileUploadID;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParentFileUploadID);
            setParentFileUploadID(refVal_setParentFileUploadID);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("filePath"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("filePath")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilePath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilePath);
            setFilePath(refVal_setFilePath);
        }
    }
    return ok;
}

void SocialPostAttachmentUpdateDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NotesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("notes")), m_Notes));
    }
    if(m_MetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("metadata")), m_Metadata));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("title")), m_Title));
    }
    if(m_AuthorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("author")), m_Author));
    }
    if(m_IsFolderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("isFolder")), m_IsFolder));
    }
    if(m_FileNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fileName")), m_FileName));
    }
    if(m_AbstractIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("abstract")), m_Abstract));
    }
    if(m_KeyWordsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("keyWords")), m_KeyWords));
    }
    if(m_ValidResponseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("validResponse")), m_ValidResponse));
    }
    if(m_ParentFileUploadIDIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("parentFileUploadID")), m_ParentFileUploadID));
    }
    if(m_FilePathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("filePath")), m_FilePath));
    }
}

bool SocialPostAttachmentUpdateDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("notes"))))
    {
        utility::string_t refVal_setNotes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("notes"))), refVal_setNotes );
        setNotes(refVal_setNotes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("metadata"))))
    {
        utility::string_t refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("author"))))
    {
        utility::string_t refVal_setAuthor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("author"))), refVal_setAuthor );
        setAuthor(refVal_setAuthor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("isFolder"))))
    {
        bool refVal_setIsFolder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("isFolder"))), refVal_setIsFolder );
        setIsFolder(refVal_setIsFolder);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("fileName"))))
    {
        utility::string_t refVal_setFileName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fileName"))), refVal_setFileName );
        setFileName(refVal_setFileName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("abstract"))))
    {
        utility::string_t refVal_setAbstract;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("abstract"))), refVal_setAbstract );
        setAbstract(refVal_setAbstract);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("keyWords"))))
    {
        utility::string_t refVal_setKeyWords;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("keyWords"))), refVal_setKeyWords );
        setKeyWords(refVal_setKeyWords);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("validResponse"))))
    {
        bool refVal_setValidResponse;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("validResponse"))), refVal_setValidResponse );
        setValidResponse(refVal_setValidResponse);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("parentFileUploadID"))))
    {
        utility::string_t refVal_setParentFileUploadID;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("parentFileUploadID"))), refVal_setParentFileUploadID );
        setParentFileUploadID(refVal_setParentFileUploadID);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("filePath"))))
    {
        utility::string_t refVal_setFilePath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("filePath"))), refVal_setFilePath );
        setFilePath(refVal_setFilePath);
    }
    return ok;
}

utility::string_t SocialPostAttachmentUpdateDto::getNotes() const
{
    return m_Notes;
}

void SocialPostAttachmentUpdateDto::setNotes(const utility::string_t& value)
{
    m_Notes = value;
    m_NotesIsSet = true;
}

bool SocialPostAttachmentUpdateDto::notesIsSet() const
{
    return m_NotesIsSet;
}

void SocialPostAttachmentUpdateDto::unsetNotes()
{
    m_NotesIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getMetadata() const
{
    return m_Metadata;
}

void SocialPostAttachmentUpdateDto::setMetadata(const utility::string_t& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}

bool SocialPostAttachmentUpdateDto::metadataIsSet() const
{
    return m_MetadataIsSet;
}

void SocialPostAttachmentUpdateDto::unsetMetadata()
{
    m_MetadataIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getTitle() const
{
    return m_Title;
}

void SocialPostAttachmentUpdateDto::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool SocialPostAttachmentUpdateDto::titleIsSet() const
{
    return m_TitleIsSet;
}

void SocialPostAttachmentUpdateDto::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getAuthor() const
{
    return m_Author;
}

void SocialPostAttachmentUpdateDto::setAuthor(const utility::string_t& value)
{
    m_Author = value;
    m_AuthorIsSet = true;
}

bool SocialPostAttachmentUpdateDto::authorIsSet() const
{
    return m_AuthorIsSet;
}

void SocialPostAttachmentUpdateDto::unsetAuthor()
{
    m_AuthorIsSet = false;
}
bool SocialPostAttachmentUpdateDto::isIsFolder() const
{
    return m_IsFolder;
}

void SocialPostAttachmentUpdateDto::setIsFolder(bool value)
{
    m_IsFolder = value;
    m_IsFolderIsSet = true;
}

bool SocialPostAttachmentUpdateDto::isFolderIsSet() const
{
    return m_IsFolderIsSet;
}

void SocialPostAttachmentUpdateDto::unsetIsFolder()
{
    m_IsFolderIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getFileName() const
{
    return m_FileName;
}

void SocialPostAttachmentUpdateDto::setFileName(const utility::string_t& value)
{
    m_FileName = value;
    m_FileNameIsSet = true;
}

bool SocialPostAttachmentUpdateDto::fileNameIsSet() const
{
    return m_FileNameIsSet;
}

void SocialPostAttachmentUpdateDto::unsetFileName()
{
    m_FileNameIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getAbstract() const
{
    return m_Abstract;
}

void SocialPostAttachmentUpdateDto::setAbstract(const utility::string_t& value)
{
    m_Abstract = value;
    m_AbstractIsSet = true;
}

bool SocialPostAttachmentUpdateDto::abstractIsSet() const
{
    return m_AbstractIsSet;
}

void SocialPostAttachmentUpdateDto::unsetAbstract()
{
    m_AbstractIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getKeyWords() const
{
    return m_KeyWords;
}

void SocialPostAttachmentUpdateDto::setKeyWords(const utility::string_t& value)
{
    m_KeyWords = value;
    m_KeyWordsIsSet = true;
}

bool SocialPostAttachmentUpdateDto::keyWordsIsSet() const
{
    return m_KeyWordsIsSet;
}

void SocialPostAttachmentUpdateDto::unsetKeyWords()
{
    m_KeyWordsIsSet = false;
}
bool SocialPostAttachmentUpdateDto::isValidResponse() const
{
    return m_ValidResponse;
}

void SocialPostAttachmentUpdateDto::setValidResponse(bool value)
{
    m_ValidResponse = value;
    m_ValidResponseIsSet = true;
}

bool SocialPostAttachmentUpdateDto::validResponseIsSet() const
{
    return m_ValidResponseIsSet;
}

void SocialPostAttachmentUpdateDto::unsetValidResponse()
{
    m_ValidResponseIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getParentFileUploadID() const
{
    return m_ParentFileUploadID;
}

void SocialPostAttachmentUpdateDto::setParentFileUploadID(const utility::string_t& value)
{
    m_ParentFileUploadID = value;
    m_ParentFileUploadIDIsSet = true;
}

bool SocialPostAttachmentUpdateDto::parentFileUploadIDIsSet() const
{
    return m_ParentFileUploadIDIsSet;
}

void SocialPostAttachmentUpdateDto::unsetParentFileUploadID()
{
    m_ParentFileUploadIDIsSet = false;
}
utility::string_t SocialPostAttachmentUpdateDto::getFilePath() const
{
    return m_FilePath;
}

void SocialPostAttachmentUpdateDto::setFilePath(const utility::string_t& value)
{
    m_FilePath = value;
    m_FilePathIsSet = true;
}

bool SocialPostAttachmentUpdateDto::filePathIsSet() const
{
    return m_FilePathIsSet;
}

void SocialPostAttachmentUpdateDto::unsetFilePath()
{
    m_FilePathIsSet = false;
}
}
}
}
}


