/**
 * AccountingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccountingEntryDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AccountingEntryDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AccountingEntryDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/Money.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Money;


/// <summary>
/// 
/// </summary>
class  AccountingEntryDto
    : public ModelBase
{
public:
    AccountingEntryDto();
    virtual ~AccountingEntryDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AccountingEntryDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimestamp() const;
    bool timestampIsSet() const;
    void unsetTimestamp();

    void setTimestamp(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    double getDebit() const;
    bool debitIsSet() const;
    void unsetDebit();

    void setDebit(double value);

    /// <summary>
    /// 
    /// </summary>
    double getCredit() const;
    bool creditIsSet() const;
    void unsetCredit();

    void setCredit(double value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();

    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getForexRate() const;
    bool forexRateIsSet() const;
    void unsetForexRate();

    void setForexRate(double value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAccountId() const;
    bool accountIdIsSet() const;
    void unsetAccountId();

    void setAccountId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();

    void setTenantId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getDate() const;
    bool dateIsSet() const;
    void unsetdate();

    void setDate(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getEnrollmentId() const;
    bool enrollmentIdIsSet() const;
    void unsetEnrollmentId();

    void setEnrollmentId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCurrencyId() const;
    bool currencyIdIsSet() const;
    void unsetCurrencyId();

    void setCurrencyId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDebitAccountId() const;
    bool debitAccountIdIsSet() const;
    void unsetDebitAccountId();

    void setDebitAccountId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCreditAccountId() const;
    bool creditAccountIdIsSet() const;
    void unsetCreditAccountId();

    void setCreditAccountId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getJournalEntryId() const;
    bool journalEntryIdIsSet() const;
    void unsetJournalEntryId();

    void setJournalEntryId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDebitAccountName() const;
    bool debitAccountNameIsSet() const;
    void unsetDebitAccountName();

    void setDebitAccountName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCreditAccountName() const;
    bool creditAccountNameIsSet() const;
    void unsetCreditAccountName();

    void setCreditAccountName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAccountingEntryType() const;
    bool accountingEntryTypeIsSet() const;
    void unsetAccountingEntryType();

    void setAccountingEntryType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Money> getDebitAmount() const;
    bool debitAmountIsSet() const;
    void unsetDebitAmount();

    void setDebitAmount(const std::shared_ptr<Money>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Money> getCreditAmount() const;
    bool creditAmountIsSet() const;
    void unsetCreditAmount();

    void setCreditAmount(const std::shared_ptr<Money>& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::datetime m_Timestamp;
    bool m_TimestampIsSet;
    double m_Debit;
    bool m_DebitIsSet;
    double m_Credit;
    bool m_CreditIsSet;
    utility::string_t m_Description;
    bool m_DescriptionIsSet;
    double m_ForexRate;
    bool m_ForexRateIsSet;
    utility::string_t m_AccountId;
    bool m_AccountIdIsSet;
    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;
    utility::datetime m_date;
    bool m_dateIsSet;
    utility::string_t m_EnrollmentId;
    bool m_EnrollmentIdIsSet;
    utility::string_t m_CurrencyId;
    bool m_CurrencyIdIsSet;
    utility::string_t m_DebitAccountId;
    bool m_DebitAccountIdIsSet;
    utility::string_t m_CreditAccountId;
    bool m_CreditAccountIdIsSet;
    utility::string_t m_JournalEntryId;
    bool m_JournalEntryIdIsSet;
    utility::string_t m_DebitAccountName;
    bool m_DebitAccountNameIsSet;
    utility::string_t m_CreditAccountName;
    bool m_CreditAccountNameIsSet;
    utility::string_t m_AccountingEntryType;
    bool m_AccountingEntryTypeIsSet;
    std::shared_ptr<Money> m_DebitAmount;
    bool m_DebitAmountIsSet;
    std::shared_ptr<Money> m_CreditAmount;
    bool m_CreditAmountIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AccountingEntryDto_H_ */
