/**
 * ProjectsService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/TaskTypeCreateDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



TaskTypeCreateDto::TaskTypeCreateDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_TaskCategoryId = utility::conversions::to_string_t("");
    m_TaskCategoryIdIsSet = false;
    m_DisplayInTimeTracker = false;
    m_DisplayInTimeTrackerIsSet = false;
    m_RequiresDescription = false;
    m_RequiresDescriptionIsSet = false;
}

TaskTypeCreateDto::~TaskTypeCreateDto()
{
}

void TaskTypeCreateDto::validate()
{
    // TODO: implement validation
}

web::json::value TaskTypeCreateDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_TitleIsSet)
    {
        val[utility::conversions::to_string_t(U("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_TaskCategoryIdIsSet)
    {
        val[utility::conversions::to_string_t(U("taskCategoryId"))] = ModelBase::toJson(m_TaskCategoryId);
    }
    if(m_DisplayInTimeTrackerIsSet)
    {
        val[utility::conversions::to_string_t(U("displayInTimeTracker"))] = ModelBase::toJson(m_DisplayInTimeTracker);
    }
    if(m_RequiresDescriptionIsSet)
    {
        val[utility::conversions::to_string_t(U("requiresDescription"))] = ModelBase::toJson(m_RequiresDescription);
    }

    return val;
}

bool TaskTypeCreateDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("taskCategoryId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("taskCategoryId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTaskCategoryId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaskCategoryId);
            setTaskCategoryId(refVal_setTaskCategoryId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("displayInTimeTracker"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("displayInTimeTracker")));
        if(!fieldValue.is_null())
        {
            bool refVal_setDisplayInTimeTracker;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisplayInTimeTracker);
            setDisplayInTimeTracker(refVal_setDisplayInTimeTracker);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("requiresDescription"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("requiresDescription")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRequiresDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequiresDescription);
            setRequiresDescription(refVal_setRequiresDescription);
        }
    }
    return ok;
}

void TaskTypeCreateDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("title")), m_Title));
    }
    if(m_TaskCategoryIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("taskCategoryId")), m_TaskCategoryId));
    }
    if(m_DisplayInTimeTrackerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("displayInTimeTracker")), m_DisplayInTimeTracker));
    }
    if(m_RequiresDescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("requiresDescription")), m_RequiresDescription));
    }
}

bool TaskTypeCreateDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("taskCategoryId"))))
    {
        utility::string_t refVal_setTaskCategoryId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("taskCategoryId"))), refVal_setTaskCategoryId );
        setTaskCategoryId(refVal_setTaskCategoryId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("displayInTimeTracker"))))
    {
        bool refVal_setDisplayInTimeTracker;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("displayInTimeTracker"))), refVal_setDisplayInTimeTracker );
        setDisplayInTimeTracker(refVal_setDisplayInTimeTracker);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("requiresDescription"))))
    {
        bool refVal_setRequiresDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("requiresDescription"))), refVal_setRequiresDescription );
        setRequiresDescription(refVal_setRequiresDescription);
    }
    return ok;
}

utility::string_t TaskTypeCreateDto::getId() const
{
    return m_Id;
}

void TaskTypeCreateDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool TaskTypeCreateDto::idIsSet() const
{
    return m_IdIsSet;
}

void TaskTypeCreateDto::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime TaskTypeCreateDto::getTimestamp() const
{
    return m_Timestamp;
}

void TaskTypeCreateDto::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool TaskTypeCreateDto::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void TaskTypeCreateDto::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
utility::string_t TaskTypeCreateDto::getTitle() const
{
    return m_Title;
}

void TaskTypeCreateDto::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool TaskTypeCreateDto::titleIsSet() const
{
    return m_TitleIsSet;
}

void TaskTypeCreateDto::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t TaskTypeCreateDto::getTaskCategoryId() const
{
    return m_TaskCategoryId;
}

void TaskTypeCreateDto::setTaskCategoryId(const utility::string_t& value)
{
    m_TaskCategoryId = value;
    m_TaskCategoryIdIsSet = true;
}

bool TaskTypeCreateDto::taskCategoryIdIsSet() const
{
    return m_TaskCategoryIdIsSet;
}

void TaskTypeCreateDto::unsetTaskCategoryId()
{
    m_TaskCategoryIdIsSet = false;
}
bool TaskTypeCreateDto::isDisplayInTimeTracker() const
{
    return m_DisplayInTimeTracker;
}

void TaskTypeCreateDto::setDisplayInTimeTracker(bool value)
{
    m_DisplayInTimeTracker = value;
    m_DisplayInTimeTrackerIsSet = true;
}

bool TaskTypeCreateDto::displayInTimeTrackerIsSet() const
{
    return m_DisplayInTimeTrackerIsSet;
}

void TaskTypeCreateDto::unsetDisplayInTimeTracker()
{
    m_DisplayInTimeTrackerIsSet = false;
}
bool TaskTypeCreateDto::isRequiresDescription() const
{
    return m_RequiresDescription;
}

void TaskTypeCreateDto::setRequiresDescription(bool value)
{
    m_RequiresDescription = value;
    m_RequiresDescriptionIsSet = true;
}

bool TaskTypeCreateDto::requiresDescriptionIsSet() const
{
    return m_RequiresDescriptionIsSet;
}

void TaskTypeCreateDto::unsetRequiresDescription()
{
    m_RequiresDescriptionIsSet = false;
}
}
}
}
}


