/**
 * SupportService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SupportRequestCreateDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SupportRequestCreateDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SupportRequestCreateDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  SupportRequestCreateDto
    : public ModelBase
{
public:
    SupportRequestCreateDto();
    virtual ~SupportRequestCreateDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SupportRequestCreateDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimestamp() const;
    bool timestampIsSet() const;
    void unsetTimestamp();

    void setTimestamp(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();

    void setTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();

    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isApproved() const;
    bool approvedIsSet() const;
    void unsetApproved();

    void setApproved(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getApprovedTimestamp() const;
    bool approvedTimestampIsSet() const;
    void unsetApprovedTimestamp();

    void setApprovedTimestamp(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSupportEntitlementId() const;
    bool supportEntitlementIdIsSet() const;
    void unsetSupportEntitlementId();

    void setSupportEntitlementId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getContactId() const;
    bool contactIdIsSet() const;
    void unsetContactId();

    void setContactId(const utility::string_t& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::datetime m_Timestamp;
    bool m_TimestampIsSet;
    utility::string_t m_Title;
    bool m_TitleIsSet;
    utility::string_t m_Description;
    bool m_DescriptionIsSet;
    bool m_Approved;
    bool m_ApprovedIsSet;
    utility::datetime m_ApprovedTimestamp;
    bool m_ApprovedTimestampIsSet;
    utility::string_t m_SupportEntitlementId;
    bool m_SupportEntitlementIdIsSet;
    utility::string_t m_ContactId;
    bool m_ContactIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SupportRequestCreateDto_H_ */
