/**
 * AccountingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/JournalDtoCollectionQueryParameters.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



JournalDtoCollectionQueryParameters::JournalDtoCollectionQueryParameters()
{
    m_Top = 0;
    m_TopIsSet = false;
    m_Skip = 0;
    m_SkipIsSet = false;
    m_Count = false;
    m_CountIsSet = false;
    m_Filter = utility::conversions::to_string_t("");
    m_FilterIsSet = false;
    m_OrderBy = utility::conversions::to_string_t("");
    m_OrderByIsSet = false;
    m_Search = utility::conversions::to_string_t("");
    m_SearchIsSet = false;
    m_Select = utility::conversions::to_string_t("");
    m_SelectIsSet = false;
    m_Expand = utility::conversions::to_string_t("");
    m_ExpandIsSet = false;
    m_IsEmpty = false;
    m_IsEmptyIsSet = false;
}

JournalDtoCollectionQueryParameters::~JournalDtoCollectionQueryParameters()
{
}

void JournalDtoCollectionQueryParameters::validate()
{
    // TODO: implement validation
}

web::json::value JournalDtoCollectionQueryParameters::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TopIsSet)
    {
        val[utility::conversions::to_string_t(U("top"))] = ModelBase::toJson(m_Top);
    }
    if(m_SkipIsSet)
    {
        val[utility::conversions::to_string_t(U("skip"))] = ModelBase::toJson(m_Skip);
    }
    if(m_CountIsSet)
    {
        val[utility::conversions::to_string_t(U("count"))] = ModelBase::toJson(m_Count);
    }
    if(m_FilterIsSet)
    {
        val[utility::conversions::to_string_t(U("filter"))] = ModelBase::toJson(m_Filter);
    }
    if(m_OrderByIsSet)
    {
        val[utility::conversions::to_string_t(U("orderBy"))] = ModelBase::toJson(m_OrderBy);
    }
    if(m_SearchIsSet)
    {
        val[utility::conversions::to_string_t(U("search"))] = ModelBase::toJson(m_Search);
    }
    if(m_SelectIsSet)
    {
        val[utility::conversions::to_string_t(U("select"))] = ModelBase::toJson(m_Select);
    }
    if(m_ExpandIsSet)
    {
        val[utility::conversions::to_string_t(U("expand"))] = ModelBase::toJson(m_Expand);
    }
    if(m_IsEmptyIsSet)
    {
        val[utility::conversions::to_string_t(U("isEmpty"))] = ModelBase::toJson(m_IsEmpty);
    }

    return val;
}

bool JournalDtoCollectionQueryParameters::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("top"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("top")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTop;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTop);
            setTop(refVal_setTop);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("skip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("skip")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSkip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSkip);
            setSkip(refVal_setSkip);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("count")));
        if(!fieldValue.is_null())
        {
            bool refVal_setCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCount);
            setCount(refVal_setCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("filter"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("filter")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilter;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilter);
            setFilter(refVal_setFilter);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("orderBy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("orderBy")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrderBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrderBy);
            setOrderBy(refVal_setOrderBy);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("search"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("search")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSearch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSearch);
            setSearch(refVal_setSearch);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("select"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("select")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSelect;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSelect);
            setSelect(refVal_setSelect);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("expand"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("expand")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExpand;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpand);
            setExpand(refVal_setExpand);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("isEmpty"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("isEmpty")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsEmpty;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsEmpty);
            setIsEmpty(refVal_setIsEmpty);
        }
    }
    return ok;
}

void JournalDtoCollectionQueryParameters::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TopIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("top")), m_Top));
    }
    if(m_SkipIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("skip")), m_Skip));
    }
    if(m_CountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("count")), m_Count));
    }
    if(m_FilterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("filter")), m_Filter));
    }
    if(m_OrderByIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("orderBy")), m_OrderBy));
    }
    if(m_SearchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("search")), m_Search));
    }
    if(m_SelectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("select")), m_Select));
    }
    if(m_ExpandIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("expand")), m_Expand));
    }
    if(m_IsEmptyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("isEmpty")), m_IsEmpty));
    }
}

bool JournalDtoCollectionQueryParameters::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("top"))))
    {
        int32_t refVal_setTop;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("top"))), refVal_setTop );
        setTop(refVal_setTop);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("skip"))))
    {
        int32_t refVal_setSkip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("skip"))), refVal_setSkip );
        setSkip(refVal_setSkip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("count"))))
    {
        bool refVal_setCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("count"))), refVal_setCount );
        setCount(refVal_setCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("filter"))))
    {
        utility::string_t refVal_setFilter;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("filter"))), refVal_setFilter );
        setFilter(refVal_setFilter);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("orderBy"))))
    {
        utility::string_t refVal_setOrderBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("orderBy"))), refVal_setOrderBy );
        setOrderBy(refVal_setOrderBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("search"))))
    {
        utility::string_t refVal_setSearch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("search"))), refVal_setSearch );
        setSearch(refVal_setSearch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("select"))))
    {
        utility::string_t refVal_setSelect;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("select"))), refVal_setSelect );
        setSelect(refVal_setSelect);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("expand"))))
    {
        utility::string_t refVal_setExpand;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("expand"))), refVal_setExpand );
        setExpand(refVal_setExpand);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("isEmpty"))))
    {
        bool refVal_setIsEmpty;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("isEmpty"))), refVal_setIsEmpty );
        setIsEmpty(refVal_setIsEmpty);
    }
    return ok;
}

int32_t JournalDtoCollectionQueryParameters::getTop() const
{
    return m_Top;
}

void JournalDtoCollectionQueryParameters::setTop(int32_t value)
{
    m_Top = value;
    m_TopIsSet = true;
}

bool JournalDtoCollectionQueryParameters::topIsSet() const
{
    return m_TopIsSet;
}

void JournalDtoCollectionQueryParameters::unsetTop()
{
    m_TopIsSet = false;
}
int32_t JournalDtoCollectionQueryParameters::getSkip() const
{
    return m_Skip;
}

void JournalDtoCollectionQueryParameters::setSkip(int32_t value)
{
    m_Skip = value;
    m_SkipIsSet = true;
}

bool JournalDtoCollectionQueryParameters::skipIsSet() const
{
    return m_SkipIsSet;
}

void JournalDtoCollectionQueryParameters::unsetSkip()
{
    m_SkipIsSet = false;
}
bool JournalDtoCollectionQueryParameters::isCount() const
{
    return m_Count;
}

void JournalDtoCollectionQueryParameters::setCount(bool value)
{
    m_Count = value;
    m_CountIsSet = true;
}

bool JournalDtoCollectionQueryParameters::countIsSet() const
{
    return m_CountIsSet;
}

void JournalDtoCollectionQueryParameters::unsetCount()
{
    m_CountIsSet = false;
}
utility::string_t JournalDtoCollectionQueryParameters::getFilter() const
{
    return m_Filter;
}

void JournalDtoCollectionQueryParameters::setFilter(const utility::string_t& value)
{
    m_Filter = value;
    m_FilterIsSet = true;
}

bool JournalDtoCollectionQueryParameters::filterIsSet() const
{
    return m_FilterIsSet;
}

void JournalDtoCollectionQueryParameters::unsetFilter()
{
    m_FilterIsSet = false;
}
utility::string_t JournalDtoCollectionQueryParameters::getOrderBy() const
{
    return m_OrderBy;
}

void JournalDtoCollectionQueryParameters::setOrderBy(const utility::string_t& value)
{
    m_OrderBy = value;
    m_OrderByIsSet = true;
}

bool JournalDtoCollectionQueryParameters::orderByIsSet() const
{
    return m_OrderByIsSet;
}

void JournalDtoCollectionQueryParameters::unsetOrderBy()
{
    m_OrderByIsSet = false;
}
utility::string_t JournalDtoCollectionQueryParameters::getSearch() const
{
    return m_Search;
}

void JournalDtoCollectionQueryParameters::setSearch(const utility::string_t& value)
{
    m_Search = value;
    m_SearchIsSet = true;
}

bool JournalDtoCollectionQueryParameters::searchIsSet() const
{
    return m_SearchIsSet;
}

void JournalDtoCollectionQueryParameters::unsetSearch()
{
    m_SearchIsSet = false;
}
utility::string_t JournalDtoCollectionQueryParameters::getSelect() const
{
    return m_Select;
}

void JournalDtoCollectionQueryParameters::setSelect(const utility::string_t& value)
{
    m_Select = value;
    m_SelectIsSet = true;
}

bool JournalDtoCollectionQueryParameters::selectIsSet() const
{
    return m_SelectIsSet;
}

void JournalDtoCollectionQueryParameters::unsetSelect()
{
    m_SelectIsSet = false;
}
utility::string_t JournalDtoCollectionQueryParameters::getExpand() const
{
    return m_Expand;
}

void JournalDtoCollectionQueryParameters::setExpand(const utility::string_t& value)
{
    m_Expand = value;
    m_ExpandIsSet = true;
}

bool JournalDtoCollectionQueryParameters::expandIsSet() const
{
    return m_ExpandIsSet;
}

void JournalDtoCollectionQueryParameters::unsetExpand()
{
    m_ExpandIsSet = false;
}
bool JournalDtoCollectionQueryParameters::isIsEmpty() const
{
    return m_IsEmpty;
}

void JournalDtoCollectionQueryParameters::setIsEmpty(bool value)
{
    m_IsEmpty = value;
    m_IsEmptyIsSet = true;
}

bool JournalDtoCollectionQueryParameters::isEmptyIsSet() const
{
    return m_IsEmptyIsSet;
}

void JournalDtoCollectionQueryParameters::unsetIsEmpty()
{
    m_IsEmptyIsSet = false;
}
}
}
}
}


