/**
 * AccountingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ShareTransferReasonDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



ShareTransferReasonDto::ShareTransferReasonDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_EnrollmentId = utility::conversions::to_string_t("");
    m_EnrollmentIdIsSet = false;
    m_TenantId = utility::conversions::to_string_t("");
    m_TenantIdIsSet = false;
}

ShareTransferReasonDto::~ShareTransferReasonDto()
{
}

void ShareTransferReasonDto::validate()
{
    // TODO: implement validation
}

web::json::value ShareTransferReasonDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TimestampIsSet)
    {
        val[utility::conversions::to_string_t(U("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        val[utility::conversions::to_string_t(U("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_EnrollmentIdIsSet)
    {
        val[utility::conversions::to_string_t(U("enrollmentId"))] = ModelBase::toJson(m_EnrollmentId);
    }
    if(m_TenantIdIsSet)
    {
        val[utility::conversions::to_string_t(U("tenantId"))] = ModelBase::toJson(m_TenantId);
    }

    return val;
}

bool ShareTransferReasonDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("enrollmentId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("enrollmentId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnrollmentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnrollmentId);
            setEnrollmentId(refVal_setEnrollmentId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tenantId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tenantId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
        }
    }
    return ok;
}

void ShareTransferReasonDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("timestamp")), m_Timestamp));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("description")), m_Description));
    }
    if(m_EnrollmentIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("enrollmentId")), m_EnrollmentId));
    }
    if(m_TenantIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tenantId")), m_TenantId));
    }
}

bool ShareTransferReasonDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("enrollmentId"))))
    {
        utility::string_t refVal_setEnrollmentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("enrollmentId"))), refVal_setEnrollmentId );
        setEnrollmentId(refVal_setEnrollmentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tenantId"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tenantId"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    return ok;
}

utility::string_t ShareTransferReasonDto::getId() const
{
    return m_Id;
}

void ShareTransferReasonDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool ShareTransferReasonDto::idIsSet() const
{
    return m_IdIsSet;
}

void ShareTransferReasonDto::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime ShareTransferReasonDto::getTimestamp() const
{
    return m_Timestamp;
}

void ShareTransferReasonDto::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool ShareTransferReasonDto::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void ShareTransferReasonDto::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
utility::string_t ShareTransferReasonDto::getName() const
{
    return m_Name;
}

void ShareTransferReasonDto::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool ShareTransferReasonDto::nameIsSet() const
{
    return m_NameIsSet;
}

void ShareTransferReasonDto::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t ShareTransferReasonDto::getDescription() const
{
    return m_Description;
}

void ShareTransferReasonDto::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool ShareTransferReasonDto::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void ShareTransferReasonDto::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t ShareTransferReasonDto::getEnrollmentId() const
{
    return m_EnrollmentId;
}

void ShareTransferReasonDto::setEnrollmentId(const utility::string_t& value)
{
    m_EnrollmentId = value;
    m_EnrollmentIdIsSet = true;
}

bool ShareTransferReasonDto::enrollmentIdIsSet() const
{
    return m_EnrollmentIdIsSet;
}

void ShareTransferReasonDto::unsetEnrollmentId()
{
    m_EnrollmentIdIsSet = false;
}
utility::string_t ShareTransferReasonDto::getTenantId() const
{
    return m_TenantId;
}

void ShareTransferReasonDto::setTenantId(const utility::string_t& value)
{
    m_TenantId = value;
    m_TenantIdIsSet = true;
}

bool ShareTransferReasonDto::tenantIdIsSet() const
{
    return m_TenantIdIsSet;
}

void ShareTransferReasonDto::unsetTenantId()
{
    m_TenantIdIsSet = false;
}
}
}
}
}


